import { 
  User, Country, Center, Schedule, Batch, Candidate, 
  PracticalTask, Worksheet, TaskAllocation, AssessorLottery, TaskLottery,
  Assessment, Result, Notification, AuditLog, Complaint, LiveActivityEvent,
  APROConfig, SerialConfig, AssessmentSettingsConfig, IDCardConfig, Reservation,
  EvaluationRubricSection, CandidateEvaluationRating, EvaluationSheet, AssessmentVarianceRecord
} from '../types';

export const DEMO_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Tariq Al-Mansoor',
    username: 'superadmin',
    email: 'superadmin@skillassess360.com',
    role: 'SUPER_ADMIN',
    status: 'ACTIVE',
    phone: '+966 50 111 2233',
    createdAt: '2026-01-10T08:00:00Z',
    lastLogin: '2026-09-17T08:30:00Z'
  },
  {
    id: 'usr-2',
    name: 'Fahad Al-Otaibi',
    username: 'country.sa',
    email: 'country.sa@skillassess360.com',
    role: 'COUNTRY_ACCOUNT',
    countryId: 'cnt-sa',
    status: 'ACTIVE',
    phone: '+966 54 222 3344',
    createdAt: '2026-01-15T09:00:00Z',
    lastLogin: '2026-09-17T07:15:00Z'
  },
  {
    id: 'usr-6',
    name: 'Zayed Al-Nahyan',
    username: 'country.ae',
    email: 'country.ae@skillassess360.com',
    role: 'COUNTRY_ACCOUNT',
    countryId: 'cnt-ae',
    status: 'ACTIVE',
    phone: '+971 50 777 8899',
    createdAt: '2026-03-01T10:00:00Z',
    lastLogin: '2026-09-16T10:30:00Z'
  },
  {
    id: 'usr-7',
    name: 'Rahim Uddin Ahmed',
    username: 'country.bd',
    email: 'country.bd@skillassess360.com',
    role: 'COUNTRY_ACCOUNT',
    countryId: 'cnt-bd',
    status: 'ACTIVE',
    phone: '+880 171 1234567',
    createdAt: '2026-03-05T09:00:00Z',
    lastLogin: '2026-09-16T08:00:00Z'
  },
  {
    id: 'usr-3',
    name: 'Dr. Khalid Al-Zahrani',
    username: 'admin.riyadh',
    email: 'center.admin@skillassess360.com',
    role: 'CENTER_ADMIN',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    status: 'ACTIVE',
    phone: '+966 56 333 4455',
    createdAt: '2026-02-01T10:00:00Z',
    lastLogin: '2026-09-17T06:45:00Z'
  },
  {
    id: 'usr-8',
    name: 'Eng. Nawaf Al-Harbi',
    username: 'admin.jeddah',
    email: 'jeddah.admin@skillassess360.com',
    role: 'CENTER_ADMIN',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-2',
    status: 'ACTIVE',
    phone: '+966 56 999 1122',
    createdAt: '2026-02-05T10:00:00Z',
    lastLogin: '2026-09-16T12:30:00Z'
  },
  {
    id: 'usr-9',
    name: 'Sultan Al-Ghamdi',
    username: 'admin.dammam',
    email: 'dammam.admin@skillassess360.com',
    role: 'CENTER_ADMIN',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-3',
    status: 'ACTIVE',
    phone: '+966 56 888 3344',
    createdAt: '2026-02-12T09:00:00Z',
    lastLogin: '2026-09-15T15:20:00Z'
  },
  {
    id: 'usr-10',
    name: 'Omar Al-Mansouri',
    username: 'admin.dubai',
    email: 'dubai.admin@skillassess360.com',
    role: 'CENTER_ADMIN',
    countryId: 'cnt-ae',
    centerId: 'ctr-ae-1',
    status: 'ACTIVE',
    phone: '+971 52 333 5566',
    createdAt: '2026-02-18T09:00:00Z',
    lastLogin: '2026-09-16T14:10:00Z'
  },
  {
    id: 'usr-11',
    name: 'Tanvir Mahmud',
    username: 'admin.dhaka',
    email: 'dhaka.admin@skillassess360.com',
    role: 'CENTER_ADMIN',
    countryId: 'cnt-bd',
    centerId: 'ctr-bd-1',
    status: 'ACTIVE',
    phone: '+880 181 9876543',
    createdAt: '2026-02-28T09:00:00Z',
    lastLogin: '2026-09-16T16:00:00Z'
  },
  {
    id: 'usr-4',
    name: 'Eng. Yasir Mahmood',
    username: 'assessor.yasir',
    email: 'assessor.lead@skillassess360.com',
    role: 'ASSESSOR',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    status: 'ACTIVE',
    phone: '+966 55 444 5566',
    assignedAssessmentsCount: 34,
    createdAt: '2026-02-10T11:30:00Z',
    lastLogin: '2026-09-17T08:00:00Z'
  },
  {
    id: 'usr-12',
    name: 'Salem Al-Dossary',
    username: 'assessor.salem',
    email: 'salem.assessor@skillassess360.com',
    role: 'ASSESSOR',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    status: 'ACTIVE',
    phone: '+966 55 111 8877',
    assignedAssessmentsCount: 22,
    createdAt: '2026-02-15T11:30:00Z',
    lastLogin: '2026-09-16T15:30:00Z'
  },
  {
    id: 'usr-13',
    name: 'Ibrahim Al-Mutawa',
    username: 'assessor.ibrahim',
    email: 'ibrahim.assessor@skillassess360.com',
    role: 'ASSESSOR',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-2',
    status: 'ACTIVE',
    phone: '+966 55 777 3322',
    assignedAssessmentsCount: 18,
    createdAt: '2026-02-20T10:00:00Z',
    lastLogin: '2026-09-15T11:45:00Z'
  },
  {
    id: 'usr-14',
    name: 'Rashid Al-Kaabi',
    username: 'assessor.rashid',
    email: 'rashid.assessor@skillassess360.com',
    role: 'ASSESSOR',
    countryId: 'cnt-ae',
    centerId: 'ctr-ae-1',
    status: 'ACTIVE',
    phone: '+971 50 222 6677',
    assignedAssessmentsCount: 28,
    createdAt: '2026-02-25T10:00:00Z',
    lastLogin: '2026-09-16T13:20:00Z'
  },
  {
    id: 'usr-15',
    name: 'Kamal Hossain',
    username: 'assessor.kamal',
    email: 'kamal.assessor@skillassess360.com',
    role: 'ASSESSOR',
    countryId: 'cnt-bd',
    centerId: 'ctr-bd-1',
    status: 'ACTIVE',
    phone: '+880 191 5556677',
    assignedAssessmentsCount: 19,
    createdAt: '2026-03-02T10:00:00Z',
    lastLogin: '2026-09-16T09:15:00Z'
  },
  {
    id: 'usr-5',
    name: 'Maryam Al-Shehri',
    username: 'staff.maryam',
    email: 'support.staff@skillassess360.com',
    role: 'SUPPORT_STAFF',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    status: 'ACTIVE',
    phone: '+966 53 555 6677',
    assignedFunction: 'Reception & Biometric Verification',
    createdAt: '2026-02-20T08:15:00Z',
    lastLogin: '2026-09-17T07:45:00Z'
  },
  {
    id: 'usr-19',
    name: 'Abdulrahman Al-Dosari',
    username: 'staff.abdulrahman',
    email: 'abdulrahman.staff@skillassess360.com',
    role: 'SUPPORT_STAFF',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    status: 'ACTIVE',
    phone: '+966 53 888 4411',
    assignedFunction: 'CBT Lab Technical Operations',
    createdAt: '2026-02-22T09:00:00Z',
    lastLogin: '2026-09-17T07:10:00Z'
  },
  {
    id: 'usr-20',
    name: 'Mona Al-Harbi',
    username: 'staff.mona',
    email: 'mona.staff@skillassess360.com',
    role: 'SUPPORT_STAFF',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    status: 'ACTIVE',
    phone: '+966 53 222 9900',
    assignedFunction: 'Practical Workshop & Tool Custodian',
    createdAt: '2026-02-25T08:30:00Z',
    lastLogin: '2026-09-16T14:30:00Z'
  },
  {
    id: 'usr-16',
    name: 'Hessa Al-Subaie',
    username: 'staff.hessa',
    email: 'hessa.staff@skillassess360.com',
    role: 'SUPPORT_STAFF',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-2',
    status: 'ACTIVE',
    phone: '+966 53 444 8899',
    createdAt: '2026-02-25T08:15:00Z',
    lastLogin: '2026-09-16T14:00:00Z'
  },
  {
    id: 'usr-17',
    name: 'Fatima Al-Zahra',
    username: 'staff.fatima',
    email: 'fatima.staff@skillassess360.com',
    role: 'SUPPORT_STAFF',
    countryId: 'cnt-ae',
    centerId: 'ctr-ae-1',
    status: 'ACTIVE',
    phone: '+971 55 999 1133',
    createdAt: '2026-03-05T08:15:00Z',
    lastLogin: '2026-09-16T11:00:00Z'
  },
  {
    id: 'usr-18',
    name: 'Anowar Hossain',
    username: 'staff.anowar',
    email: 'anowar.staff@skillassess360.com',
    role: 'SUPPORT_STAFF',
    countryId: 'cnt-bd',
    centerId: 'ctr-bd-1',
    status: 'ACTIVE',
    phone: '+880 161 7778899',
    createdAt: '2026-03-08T08:15:00Z',
    lastLogin: '2026-09-16T10:00:00Z'
  }
];

export const DEMO_COUNTRIES: Country[] = [
  {
    id: 'cnt-sa',
    code: 'SA',
    nameEn: 'Saudi Arabia',
    nameAr: 'المملكة العربية السعودية',
    flagEmoji: '🇸🇦',
    region: 'Middle East',
    status: 'ACTIVE',
    totalCenters: 3,
    contactPerson: 'Fahad Al-Otaibi',
    contactEmail: 'contact.sa@skillassess360.com',
    createdAt: '2026-01-15T00:00:00Z'
  },
  {
    id: 'cnt-ae',
    code: 'AE',
    nameEn: 'United Arab Emirates',
    nameAr: 'الإمارات العربية المتحدة',
    flagEmoji: '🇦🇪',
    region: 'Middle East',
    status: 'ACTIVE',
    totalCenters: 2,
    contactPerson: 'Zayed Al-Nahyan',
    contactEmail: 'contact.ae@skillassess360.com',
    createdAt: '2026-02-01T00:00:00Z'
  },
  {
    id: 'cnt-bd',
    code: 'BD',
    nameEn: 'Bangladesh',
    nameAr: 'بنغلاديش',
    flagEmoji: '🇧🇩',
    region: 'South Asia',
    status: 'ACTIVE',
    totalCenters: 2,
    contactPerson: 'Rahim Uddin Ahmed',
    contactEmail: 'contact.bd@skillassess360.com',
    createdAt: '2026-02-15T00:00:00Z'
  }
];

export const DEMO_CENTERS: Center[] = [
  {
    id: 'ctr-sa-1',
    code: 'CTR-SA-001',
    nameEn: 'Riyadh Central Technical Hub',
    nameAr: 'مركز الرياض الرئيسي للتقييم التقني',
    countryId: 'cnt-sa',
    city: 'Riyadh',
    address: 'King Fahad Road, Al Olaya District',
    status: 'ACTIVE',
    capacity: 120,
    occupationsSupported: ['Electrical Installation', 'HVAC Maintenance', 'Plumbing'],
    contactEmail: 'riyadh.hub@skillassess360.com',
    contactPhone: '+966 11 456 7890',
    createdAt: '2026-02-01T00:00:00Z'
  },
  {
    id: 'ctr-sa-2',
    code: 'CTR-SA-002',
    nameEn: 'Jeddah Coastal Vocational Center',
    nameAr: 'مركز جدة الساحلي المهني',
    countryId: 'cnt-sa',
    city: 'Jeddah',
    address: 'Al Madinah Al Munawwarah Rd, Al Bawadi',
    status: 'ACTIVE',
    capacity: 90,
    occupationsSupported: ['Automotive Diagnostics', 'Welding & Fabrication'],
    contactEmail: 'jeddah.center@skillassess360.com',
    contactPhone: '+966 12 654 3210',
    createdAt: '2026-02-05T00:00:00Z'
  },
  {
    id: 'ctr-sa-3',
    code: 'CTR-SA-003',
    nameEn: 'Dammam Industrial Skills Academy',
    nameAr: 'أكاديمية الدمام للمهارات الصناعية',
    countryId: 'cnt-sa',
    city: 'Dammam',
    address: 'First Industrial City, Street 14',
    status: 'ACTIVE',
    capacity: 80,
    occupationsSupported: ['Heavy Equipment Operation', 'Industrial Electrical'],
    contactEmail: 'dammam.skills@skillassess360.com',
    contactPhone: '+966 13 888 9900',
    createdAt: '2026-02-10T00:00:00Z'
  },
  {
    id: 'ctr-ae-1',
    code: 'CTR-AE-001',
    nameEn: 'Dubai Skill Excellence Campus',
    nameAr: 'مجمع دبي للتميز المهني والتقني',
    countryId: 'cnt-ae',
    city: 'Dubai',
    address: 'Al Quoz Industrial Area 3',
    status: 'ACTIVE',
    capacity: 150,
    occupationsSupported: ['Electrical Installation', 'HVAC Maintenance', 'BMS Automation'],
    contactEmail: 'dubai.hub@skillassess360.com',
    contactPhone: '+971 4 333 4455',
    createdAt: '2026-02-15T00:00:00Z'
  },
  {
    id: 'ctr-ae-2',
    code: 'CTR-AE-002',
    nameEn: 'Abu Dhabi Technical Testing Center',
    nameAr: 'مركز أبوظبي للاختبارات الفنية',
    countryId: 'cnt-ae',
    city: 'Abu Dhabi',
    address: 'Musaffah Industrial Sector 9',
    status: 'ACTIVE',
    capacity: 100,
    occupationsSupported: ['Welding & Fabrication', 'Pipe Fitting'],
    contactEmail: 'abudhabi.center@skillassess360.com',
    contactPhone: '+971 2 555 6677',
    createdAt: '2026-02-20T00:00:00Z'
  },
  {
    id: 'ctr-bd-1',
    code: 'CTR-BD-001',
    nameEn: 'Dhaka National Skill Testing Center',
    nameAr: 'مركز دكا الوطني لاختبار المهارات',
    countryId: 'cnt-bd',
    city: 'Dhaka',
    address: 'Mirpur Technical Zone, Sector 2',
    status: 'ACTIVE',
    capacity: 140,
    occupationsSupported: ['Electrical Installation', 'Plumbing', 'Carpentry'],
    contactEmail: 'dhaka.center@skillassess360.com',
    contactPhone: '+880 2 9876543',
    createdAt: '2026-02-25T00:00:00Z'
  },
  {
    id: 'ctr-bd-2',
    code: 'CTR-BD-002',
    nameEn: 'Chittagong Maritime & Mechanical Hub',
    nameAr: 'مركز شيتاغونغ للمهارات الميكانيكية والبحرية',
    countryId: 'cnt-bd',
    city: 'Chittagong',
    address: 'Agrabad Commercial Area',
    status: 'ACTIVE',
    capacity: 75,
    occupationsSupported: ['Welding & Fabrication', 'Marine Mechanics'],
    contactEmail: 'ctg.hub@skillassess360.com',
    contactPhone: '+880 31 712345',
    createdAt: '2026-03-01T00:00:00Z'
  }
];

export const DEMO_BATCHES: Batch[] = [
  {
    id: 'bat-1',
    batchNumber: 'BATCH-2026-081',
    batchName: 'Riyadh Electrical Cohort Alpha',
    sessionId: 'SES-2026-RYD-01',
    centerId: 'ctr-sa-1',
    occupation: 'Electrical Installation',
    candidateCapacity: 30,
    candidateCount: 25,
    startDate: '2026-09-10',
    endDate: '2026-09-20',
    assessmentDate: '2026-09-18',
    assessmentTime: '09:00',
    status: 'ACTIVE'
  },
  {
    id: 'bat-2',
    batchNumber: 'BATCH-2026-082',
    batchName: 'Riyadh HVAC Technicians Cohort Beta',
    sessionId: 'SES-2026-RYD-02',
    centerId: 'ctr-sa-1',
    occupation: 'HVAC Maintenance',
    candidateCapacity: 25,
    candidateCount: 20,
    startDate: '2026-09-12',
    endDate: '2026-09-22',
    assessmentDate: '2026-09-19',
    assessmentTime: '14:00',
    status: 'ACTIVE'
  },
  {
    id: 'bat-3',
    batchNumber: 'BATCH-2026-083',
    batchName: 'Jeddah Welding Specialists Batch',
    sessionId: 'SES-2026-JED-01',
    centerId: 'ctr-sa-2',
    occupation: 'Welding & Fabrication',
    candidateCapacity: 20,
    candidateCount: 18,
    startDate: '2026-09-14',
    endDate: '2026-09-24',
    assessmentDate: '2026-09-20',
    assessmentTime: '08:30',
    status: 'ACTIVE'
  },
  {
    id: 'bat-4',
    batchNumber: 'BATCH-2026-084',
    batchName: 'Dubai Automation Systems Group',
    sessionId: 'SES-2026-DXB-01',
    centerId: 'ctr-ae-1',
    occupation: 'BMS Automation',
    candidateCapacity: 35,
    candidateCount: 30,
    startDate: '2026-09-15',
    endDate: '2026-09-25',
    assessmentDate: '2026-09-21',
    assessmentTime: '09:00',
    status: 'PENDING'
  },
  {
    id: 'bat-5',
    batchNumber: 'BATCH-2026-085',
    batchName: 'Dhaka Hydraulic & Plumbing Cohort',
    sessionId: 'SES-2026-DHK-01',
    centerId: 'ctr-bd-1',
    occupation: 'Plumbing',
    candidateCapacity: 25,
    candidateCount: 22,
    startDate: '2026-09-16',
    endDate: '2026-09-26',
    assessmentDate: '2026-09-22',
    assessmentTime: '10:00',
    status: 'ACTIVE'
  },
  {
    id: 'bat-6',
    batchNumber: 'BATCH-2026-086',
    batchName: 'Dammam Industrial Electrical Batch',
    sessionId: 'SES-2026-DAM-01',
    centerId: 'ctr-sa-3',
    occupation: 'Industrial Electrical',
    candidateCapacity: 20,
    candidateCount: 16,
    startDate: '2026-09-18',
    endDate: '2026-09-28',
    assessmentDate: '2026-09-23',
    assessmentTime: '09:00',
    status: 'PENDING'
  }
];

export const DEMO_SCHEDULES: Schedule[] = [
  {
    id: 'sch-1',
    code: 'SCH-2026-091',
    centerId: 'ctr-sa-1',
    countryId: 'cnt-sa',
    occupation: 'Electrical Installation',
    date: '2026-09-18',
    timeSlot: '09:00 - 13:00',
    startTime: '09:00',
    endTime: '13:00',
    totalSeats: 25,
    assignedCandidates: 25,
    assessorCount: 2,
    assessorId: 'usr-4',
    status: 'SCHEDULED',
    notes: 'Morning evaluation session for residential distribution boards and containment.',
    createdAt: '2026-09-10T08:00:00Z'
  },
  {
    id: 'sch-2',
    code: 'SCH-2026-092',
    centerId: 'ctr-sa-1',
    countryId: 'cnt-sa',
    occupation: 'HVAC Maintenance',
    date: '2026-09-19',
    timeSlot: '14:00 - 18:00',
    startTime: '14:00',
    endTime: '18:00',
    totalSeats: 20,
    assignedCandidates: 18,
    assessorCount: 2,
    assessorId: 'usr-4',
    status: 'SCHEDULED',
    notes: 'Afternoon practical session testing split-unit recovery, leak vacuum, and re-gas.',
    createdAt: '2026-09-11T09:30:00Z'
  },
  {
    id: 'sch-3',
    code: 'SCH-2026-093',
    centerId: 'ctr-sa-2',
    countryId: 'cnt-sa',
    occupation: 'Welding & Fabrication',
    date: '2026-09-20',
    timeSlot: '08:30 - 12:30',
    startTime: '08:30',
    endTime: '12:30',
    totalSeats: 18,
    assignedCandidates: 18,
    assessorCount: 2,
    assessorId: 'usr-13',
    status: 'SCHEDULED',
    notes: 'TIG & SMAW 3F position fillet joint evaluation at Bay 1-6.',
    createdAt: '2026-09-12T10:00:00Z'
  },
  {
    id: 'sch-4',
    code: 'SCH-2026-094',
    centerId: 'ctr-ae-1',
    countryId: 'cnt-ae',
    occupation: 'BMS Automation',
    date: '2026-09-21',
    timeSlot: '09:00 - 13:00',
    startTime: '09:00',
    endTime: '13:00',
    totalSeats: 30,
    assignedCandidates: 28,
    assessorCount: 3,
    assessorId: 'usr-14',
    status: 'SCHEDULED',
    notes: 'BacNet DDC controller programming and sensor loop calibration.',
    createdAt: '2026-09-13T11:00:00Z'
  },
  {
    id: 'sch-5',
    code: 'SCH-2026-095',
    centerId: 'ctr-bd-1',
    countryId: 'cnt-bd',
    occupation: 'Plumbing',
    date: '2026-09-22',
    timeSlot: '10:00 - 14:00',
    startTime: '10:00',
    endTime: '14:00',
    totalSeats: 22,
    assignedCandidates: 20,
    assessorCount: 2,
    assessorId: 'usr-15',
    status: 'SCHEDULED',
    notes: 'PPR pipe welding, pressure test manifold assembly, and sanitary traps.',
    createdAt: '2026-09-14T09:00:00Z'
  }
];

export const DEMO_CANDIDATES: Candidate[] = [
  {
    id: 'can-1',
    fullNameEn: 'Mohammed Alamgir Hossain',
    fullNameAr: 'محمد عالمجير حسين',
    passportNumber: 'EB0982714',
    aproReference: 'APRO-SA-92812',
    nationalId: '1992451892',
    occupation: 'Electrical Installation',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    batchId: 'bat-1',
    scheduleId: 'sch-1',
    reservationId: 'RES-2026-SA-1001',
    enrollmentStatus: 'ENROLLED',
    preloadStatus: 'PRELOADED',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    cbtStatus: 'COMPLETED',
    cbtStartTime: '2026-09-18T09:15:00Z',
    cbtEndTime: '2026-09-18T10:05:00Z',
    cbtScore: 88,
    practicalStatus: 'IN_PROGRESS',
    assignedTaskId: 'tsk-1',
    assignedTaskCode: 'TSK-ELE-01',
    assignedTaskTitle: 'Three-Phase Distribution Board & Circuit Protection Installation',
    taskDifficulty: 'INTERMEDIATE',
    taskAssignedAt: '2026-09-18T08:45:00Z',
    assessorId: 'usr-4',
    assessorName: 'Eng. Yasir Mahmood',
    assessorLotteryStatus: 'HIDDEN',
    evidenceStatus: 'UPLOADED',
    evidenceItems: [
      {
        id: 'ev-101',
        type: 'WORKPIECE_PHOTO',
        title: 'Cable termination and conduit trunking alignment',
        uploadedAt: '2026-09-18T11:20:00Z',
        uploadedBy: 'Eng. Yasir Mahmood',
        status: 'VERIFIED'
      },
      {
        id: 'ev-102',
        type: 'SAFETY_CHECK',
        title: 'Personal protective equipment & lockout tagout compliance',
        uploadedAt: '2026-09-18T09:10:00Z',
        uploadedBy: 'Eng. Yasir Mahmood',
        status: 'VERIFIED'
      }
    ],
    evaluationStatus: 'IN_PROGRESS',
    status: 'IN_ASSESSMENT',
    registeredAt: '2026-09-10T08:00:00Z',
    enrolledAt: '2026-09-18T08:45:00Z',
    idCardStatus: 'GENERATED',
    idCardNumber: 'IDC-SA-2026-00481',
    idCardGeneratedAt: '2026-09-18T12:00:00Z',
    supportStaffVerificationStatus: 'CONFIRMED',
    supportStaffConfirmationDate: '19/09/2026',
    supportStaffConfirmationTime: '09:30 AM',
    supportStaffVerifiedBy: 'Anowar Hossain',
    passportMatchConfirmed: true,
    passportVerificationPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'can-2',
    fullNameEn: 'Abdul Karim Mansoor',
    fullNameAr: 'عبد الكريم منصور',
    passportNumber: 'FA8872190',
    aproReference: 'APRO-SA-92813',
    nationalId: '1989332140',
    occupation: 'Electrical Installation',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    batchId: 'bat-1',
    scheduleId: 'sch-1',
    reservationId: 'RES-2026-SA-1002',
    enrollmentStatus: 'ENROLLED',
    preloadStatus: 'PRELOADED',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    cbtStatus: 'COMPLETED',
    cbtScore: 85,
    practicalStatus: 'NOT_STARTED',
    assignedTaskId: 'tsk-1',
    assignedTaskCode: 'TSK-ELE-01',
    assignedTaskTitle: 'Three-Phase Distribution Board & Circuit Protection Installation',
    taskDifficulty: 'INTERMEDIATE',
    assessorId: 'usr-4',
    assessorName: 'Eng. Yasir Mahmood',
    assessorLotteryStatus: 'RELEASED',
    evidenceStatus: 'NOT_UPLOADED',
    status: 'ASSIGNED',
    registeredAt: '2026-09-10T08:30:00Z',
    idCardStatus: 'REQUESTED',
    supportStaffVerificationStatus: 'CONFIRMED',
    supportStaffConfirmationDate: '19/09/2026',
    supportStaffConfirmationTime: '09:45 AM',
    supportStaffVerifiedBy: 'Anowar Hossain',
    passportMatchConfirmed: true,
    passportVerificationPhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    exitStatus: 'CONFIRMED',
    exitConfirmationDate: '19/09/2026',
    exitConfirmationTime: '11:45 AM',
    exitVerifiedBy: 'Anowar Hossain',
    exitNotes: 'Candidate completed all workstation tasks and returned equipment.',
  },
  {
    id: 'can-3',
    fullNameEn: 'Shahidul Islam Mia',
    fullNameAr: 'شهيد الإسلام ميا',
    passportNumber: 'BL7329188',
    aproReference: 'APRO-SA-92814',
    nationalId: '1994119823',
    occupation: 'HVAC Maintenance',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    batchId: 'bat-2',
    scheduleId: 'sch-2',
    reservationId: 'RES-2026-SA-1003',
    enrollmentStatus: 'ENROLLED',
    preloadStatus: 'PRELOADED',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    cbtStatus: 'COMPLETED',
    cbtStartTime: '2026-09-19T14:15:00Z',
    cbtEndTime: '2026-09-19T15:00:00Z',
    cbtScore: 82,
    practicalStatus: 'COMPLETED',
    assignedTaskId: 'tsk-2',
    assignedTaskCode: 'TSK-HVC-02',
    assignedTaskTitle: 'Split-System Refrigerant Recovery, Vacuum Testing & Commissioning',
    taskDifficulty: 'ADVANCED',
    taskAssignedAt: '2026-09-19T13:45:00Z',
    assessorId: 'usr-4',
    assessorName: 'Eng. Yasir Mahmood',
    assessorLotteryStatus: 'RELEASED',
    evidenceStatus: 'VERIFIED',
    evidenceItems: [
      {
        id: 'ev-103',
        type: 'WORKPIECE_PHOTO',
        title: 'Vacuum manifold gauge reading 500 microns',
        uploadedAt: '2026-09-19T16:10:00Z',
        uploadedBy: 'Eng. Yasir Mahmood',
        status: 'VERIFIED'
      },
      {
        id: 'ev-104',
        type: 'SAFETY_CHECK',
        title: 'Refrigerant recovery cylinder pressure seal certification',
        uploadedAt: '2026-09-19T16:20:00Z',
        uploadedBy: 'Eng. Yasir Mahmood',
        status: 'VERIFIED'
      }
    ],
    evaluationStatus: 'PENDING',
    status: 'EVALUATION_PENDING',
    resultStatus: 'PENDING',
    registeredAt: '2026-09-11T09:10:00Z',
    enrolledAt: '2026-09-19T13:45:00Z',
    idCardStatus: 'APPROVED'
  },
  {
    id: 'can-4',
    fullNameEn: 'Kamal Pasha Rashed',
    fullNameAr: 'كمال باشا راشد',
    passportNumber: 'EG4190822',
    aproReference: 'APRO-SA-92815',
    nationalId: '1987554901',
    occupation: 'Welding & Fabrication',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-2',
    batchId: 'bat-3',
    scheduleId: 'sch-3',
    reservationId: 'RES-2026-SA-2001',
    enrollmentStatus: 'ENROLLED',
    preloadStatus: 'PRELOADED',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    cbtStatus: 'COMPLETED',
    cbtScore: 91,
    practicalStatus: 'COMPLETED',
    assignedTaskId: 'tsk-3',
    assignedTaskCode: 'TSK-WLD-03',
    assignedTaskTitle: 'Shielded Metal Arc Welding 3F Vertical Fillet Joint Evaluation',
    taskDifficulty: 'ADVANCED',
    assessorId: 'usr-13',
    assessorName: 'Ibrahim Al-Mutawa',
    assessorLotteryStatus: 'RELEASED',
    evidenceStatus: 'VERIFIED',
    status: 'EVALUATED',
    resultStatus: 'PASS',
    registeredAt: '2026-09-12T10:00:00Z',
    enrolledAt: '2026-09-20T08:00:00Z',
    idCardStatus: 'GENERATED',
    idCardNumber: 'IDC-SA-2026-00482',
    idCardGeneratedAt: '2026-09-17T15:30:00Z'
  },
  {
    id: 'can-5',
    fullNameEn: 'Tarique Anowar',
    fullNameAr: 'طارق أنور',
    passportNumber: 'BD5410982',
    aproReference: 'APRO-AE-81729',
    nationalId: '1991884729',
    occupation: 'BMS Automation',
    countryId: 'cnt-ae',
    centerId: 'ctr-ae-1',
    batchId: 'bat-4',
    scheduleId: 'sch-4',
    reservationId: 'RES-2026-AE-3001',
    enrollmentStatus: 'NOT_ENROLLED',
    preloadStatus: 'PRELOADED',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    status: 'SCHEDULED',
    registeredAt: '2026-09-13T11:00:00Z',
    idCardStatus: 'NOT_REQUESTED'
  },
  {
    id: 'can-6',
    fullNameEn: 'Mahfuzur Rahman',
    fullNameAr: 'محفوظ الرحمن',
    passportNumber: 'BK9928371',
    aproReference: 'APRO-SA-92816',
    nationalId: '1993228912',
    occupation: 'Electrical Installation',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    batchId: 'bat-1',
    scheduleId: 'sch-1',
    reservationId: 'RES-2026-SA-1001',
    enrollmentStatus: 'ENROLLED',
    preloadStatus: 'PRELOADED',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    cbtStatus: 'COMPLETED',
    cbtScore: 92,
    practicalStatus: 'COMPLETED',
    assignedTaskId: 'tsk-1',
    assignedTaskCode: 'TSK-ELE-01',
    assignedTaskTitle: 'Three-Phase Distribution Board & Circuit Protection Installation',
    taskDifficulty: 'INTERMEDIATE',
    assessorId: 'usr-4',
    assessorName: 'Eng. Yasir Mahmood',
    assessorLotteryStatus: 'RELEASED',
    evidenceStatus: 'VERIFIED',
    evaluationStatus: 'COMPLETED',
    status: 'LOCKED',
    resultLocked: true,
    resultStatus: 'PASS',
    registeredAt: '2026-09-08T07:45:00Z',
    enrolledAt: '2026-09-18T08:00:00Z'
  },
  {
    id: 'can-7',
    fullNameEn: 'Nasser Saeed Al-Ghamdi',
    fullNameAr: 'ناصر سعيد الغامدي',
    passportNumber: 'SA1092834',
    aproReference: 'APRO-SA-92817',
    nationalId: '1088223344',
    occupation: 'Automotive Diagnostics',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-2',
    batchId: 'bat-3',
    status: 'SCHEDULED',
    registeredAt: '2026-09-12T14:10:00Z'
  },
  {
    id: 'can-8',
    fullNameEn: 'Zubair Bin Khalid',
    fullNameAr: 'زبير بن خالد',
    passportNumber: 'AE8829103',
    aproReference: 'APRO-AE-81730',
    nationalId: '7841990234',
    occupation: 'BMS Automation',
    countryId: 'cnt-ae',
    centerId: 'ctr-ae-1',
    batchId: 'bat-4',
    status: 'IN_ASSESSMENT',
    registeredAt: '2026-09-13T15:00:00Z'
  },
  {
    id: 'can-9',
    fullNameEn: 'Rashedul Islam Chowdhury',
    fullNameAr: 'راشد الإسلام تشودري',
    passportNumber: 'BD1129485',
    aproReference: 'APRO-BD-70011',
    nationalId: '1996558832',
    occupation: 'Plumbing',
    countryId: 'cnt-bd',
    centerId: 'ctr-bd-1',
    batchId: 'bat-5',
    scheduleId: 'sch-5',
    status: 'SCHEDULED',
    registeredAt: '2026-09-14T09:30:00Z'
  },
  {
    id: 'can-10',
    fullNameEn: 'Moniruzzaman Sarkar',
    fullNameAr: 'منير الزمان سركار',
    passportNumber: 'BD3392817',
    aproReference: 'APRO-BD-70012',
    nationalId: '1990117765',
    occupation: 'Plumbing',
    countryId: 'cnt-bd',
    centerId: 'ctr-bd-1',
    batchId: 'bat-5',
    scheduleId: 'sch-5',
    status: 'REGISTERED',
    registeredAt: '2026-09-14T10:00:00Z'
  },
  {
    id: 'can-11',
    fullNameEn: 'Saud Abdulaziz Al-Mutairi',
    fullNameAr: 'سعود عبد العزيز المطيري',
    passportNumber: 'SA4490182',
    aproReference: 'APRO-SA-92818',
    nationalId: '1099887711',
    occupation: 'Industrial Electrical',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-3',
    batchId: 'bat-6',
    status: 'REGISTERED',
    registeredAt: '2026-09-15T08:00:00Z'
  },
  {
    id: 'can-12',
    fullNameEn: 'Hassan Ali Al-Marzouqi',
    fullNameAr: 'حسن علي المرزوقي',
    passportNumber: 'AE3391029',
    aproReference: 'APRO-AE-81731',
    nationalId: '7841988112',
    occupation: 'Pipe Fitting',
    countryId: 'cnt-ae',
    centerId: 'ctr-ae-1',
    batchId: 'bat-4',
    status: 'SCHEDULED',
    registeredAt: '2026-09-15T11:45:00Z'
  },
  {
    id: 'can-13',
    fullNameEn: 'Iqbal Kabir',
    fullNameAr: 'إقبال كبير',
    passportNumber: 'BD8827104',
    aproReference: 'APRO-BD-70013',
    nationalId: '1992664411',
    occupation: 'Electrical Installation',
    countryId: 'cnt-bd',
    centerId: 'ctr-bd-1',
    batchId: 'bat-5',
    status: 'SCHEDULED',
    registeredAt: '2026-09-15T13:00:00Z'
  },
  {
    id: 'can-14',
    fullNameEn: 'Farhan Tariq Al-Bishi',
    fullNameAr: 'فرحان طارق البيشي',
    passportNumber: 'SA7719284',
    aproReference: 'APRO-SA-92819',
    nationalId: '1077665544',
    occupation: 'HVAC Maintenance',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    batchId: 'bat-2',
    scheduleId: 'sch-2',
    enrollmentStatus: 'ENROLLED',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    cbtStatus: 'COMPLETED',
    cbtScore: 89,
    assignedTaskId: 'tsk-2',
    assignedTaskCode: 'TSK-HVC-02',
    assignedTaskTitle: 'Split-System Refrigerant Recovery, Vacuum Testing & Commissioning',
    taskDifficulty: 'ADVANCED',
    assessorId: 'usr-4',
    assessorName: 'Eng. Yasir Mahmood',
    assessorLotteryStatus: 'RELEASED',
    status: 'VERIFIED',
    practicalStatus: 'NOT_STARTED',
    evidenceStatus: 'NOT_UPLOADED',
    resultStatus: 'PENDING',
    registeredAt: '2026-09-11T10:15:00Z'
  },
  {
    id: 'can-15',
    fullNameEn: 'Ahmed Saeed Al-Shehhi',
    fullNameAr: 'أحمد سعيد الشحي',
    passportNumber: 'AE9918273',
    aproReference: 'APRO-AE-81732',
    nationalId: '7841993445',
    occupation: 'Electrical Installation',
    countryId: 'cnt-ae',
    centerId: 'ctr-ae-1',
    batchId: 'bat-4',
    status: 'COMPLETED',
    resultStatus: 'PASS',
    registeredAt: '2026-09-09T09:00:00Z'
  },
  {
    id: 'can-16',
    fullNameEn: 'Bilal Hussain Shah',
    fullNameAr: 'بلال حسين شاه',
    passportNumber: 'PK8819203',
    aproReference: 'APRO-SA-92820',
    nationalId: '1988229911',
    occupation: 'Welding & Fabrication',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-2',
    batchId: 'bat-3',
    scheduleId: 'sch-3',
    assessorId: 'usr-13',
    status: 'EVALUATED',
    resultStatus: 'FAIL',
    registeredAt: '2026-09-12T11:00:00Z'
  },
  {
    id: 'can-17',
    fullNameEn: 'Majid Al-Dhaheri',
    fullNameAr: 'ماجد الظاهري',
    passportNumber: 'AE4410293',
    aproReference: 'APRO-AE-81733',
    nationalId: '7841995112',
    occupation: 'Welding & Fabrication',
    countryId: 'cnt-ae',
    centerId: 'ctr-ae-1',
    batchId: 'bat-4',
    status: 'SCHEDULED',
    registeredAt: '2026-09-14T14:00:00Z'
  },
  {
    id: 'can-18',
    fullNameEn: 'Delwar Hossain',
    fullNameAr: 'دلوار حسين',
    passportNumber: 'BD6619283',
    aproReference: 'APRO-BD-70014',
    nationalId: '1993881122',
    occupation: 'Carpentry',
    countryId: 'cnt-bd',
    centerId: 'ctr-bd-1',
    batchId: 'bat-5',
    status: 'REGISTERED',
    registeredAt: '2026-09-15T15:30:00Z'
  },
  {
    id: 'can-19',
    fullNameEn: 'Faisal Mohammed Al-Otaibi',
    fullNameAr: 'فيصل محمد العتيبي',
    passportNumber: 'SA5591028',
    aproReference: 'APRO-SA-92821',
    nationalId: '1066554433',
    occupation: 'Electrical Installation',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    batchId: 'bat-1',
    scheduleId: 'sch-1',
    enrollmentStatus: 'ENROLLED',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    cbtStatus: 'COMPLETED',
    cbtScore: 78,
    assignedTaskId: 'tsk-1',
    assignedTaskCode: 'TSK-ELE-01',
    assignedTaskTitle: 'Three-Phase Distribution Board & Circuit Protection Installation',
    taskDifficulty: 'INTERMEDIATE',
    assessorId: 'usr-4',
    assessorName: 'Eng. Yasir Mahmood',
    assessorLotteryStatus: 'RELEASED',
    status: 'PRACTICAL_COMPLETED',
    practicalStatus: 'COMPLETED',
    evidenceStatus: 'NOT_UPLOADED',
    resultStatus: 'PENDING',
    registeredAt: '2026-09-10T12:00:00Z'
  },
  {
    id: 'can-20',
    fullNameEn: 'Nurul Islam Talukder',
    fullNameAr: 'نور الإسلام تالوكدار',
    passportNumber: 'BD9910284',
    aproReference: 'APRO-BD-70015',
    nationalId: '1991443322',
    occupation: 'Marine Mechanics',
    countryId: 'cnt-bd',
    centerId: 'ctr-bd-1',
    batchId: 'bat-5',
    status: 'REGISTERED',
    registeredAt: '2026-09-16T08:00:00Z'
  },
  {
    id: 'can-21',
    fullNameEn: 'Saad Abdullah Al-Qarni',
    fullNameAr: 'سعد عبد الله القرني',
    passportNumber: 'SA1190284',
    aproReference: 'APRO-SA-92822',
    nationalId: '1055443322',
    occupation: 'HVAC Maintenance',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    batchId: 'bat-2',
    scheduleId: 'sch-2',
    enrollmentStatus: 'ENROLLED',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    cbtStatus: 'COMPLETED',
    cbtScore: 80,
    assignedTaskId: 'tsk-2',
    assignedTaskCode: 'TSK-HVC-02',
    assignedTaskTitle: 'Split-System Refrigerant Recovery, Vacuum Testing & Commissioning',
    taskDifficulty: 'ADVANCED',
    assessorId: 'usr-4',
    assessorName: 'Eng. Yasir Mahmood',
    assessorLotteryStatus: 'RELEASED',
    status: 'ASSIGNED',
    practicalStatus: 'NOT_STARTED',
    evidenceStatus: 'NOT_UPLOADED',
    resultStatus: 'PENDING',
    registeredAt: '2026-09-11T11:45:00Z'
  },
  {
    id: 'can-22',
    fullNameEn: 'Khalid Masood',
    fullNameAr: 'خالد مسعود',
    passportNumber: 'PK7719203',
    aproReference: 'APRO-SA-92823',
    nationalId: '1987332211',
    occupation: 'Plumbing',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    batchId: 'bat-1',
    scheduleId: 'sch-1',
    status: 'SCHEDULED',
    registeredAt: '2026-09-10T13:00:00Z'
  }
];

export const DEMO_TASKS: PracticalTask[] = [
  {
    id: 'tsk-1',
    code: 'TSK-ELE-01',
    titleEn: 'Three-Phase Motor Control Circuit Wiring & Troubleshooting',
    titleAr: 'توصيل واكتشاف أعطال دائرة التحكم في محرك ثلاثي الأطوار',
    occupation: 'Electrical Installation',
    difficulty: 'INTERMEDIATE',
    practicalWork: 'Install, wire, verify phase balance and calibrate overload contactor on standard DOL control board.',
    toolsAndEquipment: ['Multimeter', 'Insulated Screwdriver Set', 'Wire Strippers', 'Lockout Tagout Kit', 'Phase Rotation Tester'],
    situation: 'Candidate is presented with an industrial control enclosure requiring full DOL starter wiring and deliberate fault injection.',
    steps: [
      'Perform lockout/tagout and confirm zero voltage verification.',
      'Mount thermal overload relay and main contactor securely on DIN rail.',
      'Wire control loop from push button station according to blueprint schematic.',
      'Check continuity and insulation resistance with 500V insulation tester.',
      'Perform energized operational run and measure full load amperage.'
    ],
    maxScore: 100,
    passingScore: 70,
    durationMinutes: 90,
    status: 'ACTIVE',
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z'
  },
  {
    id: 'tsk-2',
    code: 'TSK-HVAC-01',
    titleEn: 'Split AC Refrigerant Evacuation, Leak Check and Charging',
    titleAr: 'تفريغ وفحص تسريب وشحن وسيط التبريد لمكيف الهواء المنفصل',
    occupation: 'HVAC Maintenance',
    difficulty: 'INTERMEDIATE',
    practicalWork: 'Connect manifold gauges, perform deep evacuation to 500 microns, nitrogen pressure hold test, and weigh in R-410A charge.',
    toolsAndEquipment: ['Digital Vacuum Gauge', '4-Valve Manifold Gauge', 'Vacuum Pump', 'Electronic Charging Scale', 'R-410A Cylinder', 'Halide Leak Detector'],
    situation: 'Residential inverter split unit with suspected micro-leak following indoor unit replacement.',
    steps: [
      'Connect digital manifold hoses with low-loss fittings.',
      'Pressurize system with dry nitrogen to 150 PSI and check flaring joints with bubble solution.',
      'Evacuate system to below 500 microns and observe 10-minute blank-off hold.',
      'Charge exact OEM refrigerant mass using calibrated electronic scale.',
      'Start unit in test cooling mode, log superheat, subcooling, and suction pressure.'
    ],
    maxScore: 100,
    passingScore: 70,
    durationMinutes: 75,
    status: 'ACTIVE',
    createdAt: '2026-02-05T08:00:00Z',
    updatedAt: '2026-09-05T12:00:00Z'
  },
  {
    id: 'tsk-3',
    code: 'TSK-WLD-01',
    titleEn: 'TIG 6G Pipe Joint Welding & Visual Defect Inspection',
    titleAr: 'لحام وصلات الأنابيب بوضع 6G وفحص العيوب البصرية',
    occupation: 'Welding & Fabrication',
    difficulty: 'ADVANCED',
    practicalWork: 'Weld carbon steel pipe 2-inch Sch 40 in 6G inclined 45° fixed position using GTAW process root with SMAW fill/cap.',
    toolsAndEquipment: ['GTAW TIG Machine', 'Argon Shielding Gas Tank', 'ER70S-6 Filler Rod', 'E7018 Electrodes', 'Grinder with Wire Wheel', 'Welding Helmet (DIN 11)'],
    situation: 'Industrial pipeline spool fabrication adhering to ASME Section IX pipe joint specifications.',
    steps: [
      'Clean bevel faces to bright metal and align 2.5mm root gap with 4 bridge tacks.',
      'Purge root cavity with 99.9% argon backing gas where mandated.',
      'Deposit keyhole root pass ensuring 100% complete penetration without burn-through.',
      'Clean interpass scale and complete fill layers with stringer bead technique.',
      'Present completed cap for visual inspection of undercut, porosity, and reinforcement height.'
    ],
    maxScore: 100,
    passingScore: 75,
    durationMinutes: 120,
    status: 'ACTIVE',
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-09-02T14:00:00Z'
  },
  {
    id: 'tsk-4',
    code: 'TSK-BMS-01',
    titleEn: 'BACnet DDC Controller Configuration & Sensor Loop Testing',
    titleAr: 'برمجة وحدة التحكم DDC عبر بروتوكول BACnet واختبار حلقات الحساسات',
    occupation: 'BMS Automation',
    difficulty: 'ADVANCED',
    practicalWork: 'Configure programmable BACnet MS/TP controller, map analog inputs/outputs, and verify PI temperature loop response.',
    toolsAndEquipment: ['Laptop with Engineering Tool', 'USB to RS-485 Adapter', 'Pt1000 Simulator', 'Digital Multimeter', '0-10V Actuator Test Rig'],
    situation: 'Commissioning of a variable air volume (VAV) terminal box controller on a multi-story building network.',
    steps: [
      'Assign MAC address and device instance ID per commissioning schedule.',
      'Configure analog inputs for temperature (10k Type 2) and differential pressure transmitter.',
      'Bind software points to physical outputs for 0-10V modulating damper actuator.',
      'Simulate room thermal load change and observe proportional integral output stability.',
      'Export network discovery scan confirming zero token-passing collision.'
    ],
    maxScore: 100,
    passingScore: 75,
    durationMinutes: 90,
    status: 'ACTIVE',
    createdAt: '2026-02-15T08:00:00Z',
    updatedAt: '2026-09-08T11:00:00Z'
  },
  {
    id: 'tsk-5',
    code: 'TSK-PLM-01',
    titleEn: 'PEX & Copper Hydrostatic Pressure Piping Manifold Installation',
    titleAr: 'تركيب موزع أنابيب PEX والنحاس واختبار الضغط الهيدروستاتيكي',
    occupation: 'Plumbing',
    difficulty: 'FOUNDATIONAL',
    practicalWork: 'Assemble potable water distribution manifold combining press-fit copper and cross-linked polyethylene (PEX-a) piping.',
    toolsAndEquipment: ['Hydrostatic Test Pump', 'Battery Press Tool', 'PEX Expansion Tool', 'Pipe Cutter', 'Pressure Gauge (0-15 bar)'],
    situation: 'Commercial washroom rough-in installation compliant with Uniform Plumbing Code (UPC).',
    steps: [
      'Cut and ream 22mm copper pipe to blueprint dimensions.',
      'Complete press-fit connections verifying depth insertion marks.',
      'Expand and seat PEX-a ring fittings onto distribution manifold branches.',
      'Fill system with water, purge trapped air completely, and apply 10 bar hydrostatic test.',
      'Hold test pressure for 30 minutes with zero observable pressure drop.'
    ],
    maxScore: 100,
    passingScore: 70,
    durationMinutes: 60,
    status: 'ACTIVE',
    createdAt: '2026-02-20T08:00:00Z',
    updatedAt: '2026-09-04T09:00:00Z'
  },
  {
    id: 'tsk-6',
    code: 'TSK-AUT-01',
    titleEn: 'CAN-Bus Network Communication & Sensor Signal Oscilloscope Diagnostics',
    titleAr: 'تشخيص شبكة اتصالات CAN-Bus وإشارات الحساسات بجهاز راسم الإشارة',
    occupation: 'Automotive Diagnostics',
    difficulty: 'ADVANCED',
    practicalWork: 'Diagnose high-speed CAN network fault, measure terminal termination resistance, and capture waveform on dual-channel lab scope.',
    toolsAndEquipment: ['Automotive Diagnostic Tablet', 'Dual-Channel Oscilloscope', 'Breakout Box', 'Digital Multimeter', 'Wiring Harness Pin Out Probes'],
    situation: 'Vehicle exhibiting intermittent communication loss between Engine Control Module (ECM) and Transmission Control Module (TCM).',
    steps: [
      'Connect OBD breakout box and measure CAN-H to CAN-L termination resistance (nominal 60 ohms).',
      'Set oscilloscope time base to 20µs and trigger on differential voltage change.',
      'Capture CAN-H (2.5V to 3.5V) and CAN-L (2.5V to 1.5V) synchronized waveform.',
      'Identify whether fault represents short to ground, short to 12V, open line, or EMI distortion.',
      'Clear stored Diagnostic Trouble Codes (DTCs) and verify active module readiness monitors.'
    ],
    maxScore: 100,
    passingScore: 75,
    durationMinutes: 80,
    status: 'ACTIVE',
    createdAt: '2026-02-25T08:00:00Z',
    updatedAt: '2026-09-06T15:00:00Z'
  }
];

export const DEMO_WORKSHEETS: Worksheet[] = [
  {
    id: 'wks-1',
    code: 'WKS-ELE-001',
    title: 'DOL Motor Starter Blueprint & Wiring Worksheet',
    occupation: 'Electrical Installation',
    taskId: 'tsk-1',
    fileName: 'DOL_Starter_Wiring_Guide_v2.pdf',
    fileSize: '2.4 MB',
    uploadedBy: 'Tariq Al-Mansoor (Super Admin)',
    uploadedAt: '2026-09-01T10:00:00Z',
    version: '2.1',
    status: 'ACTIVE'
  },
  {
    id: 'wks-2',
    code: 'WKS-HVAC-002',
    title: 'R-410A Refrigerant Pressure-Temperature Chart & Checklist',
    occupation: 'HVAC Maintenance',
    taskId: 'tsk-2',
    fileName: 'HVAC_Evacuation_Logsheet_2026.pdf',
    fileSize: '1.8 MB',
    uploadedBy: 'Tariq Al-Mansoor (Super Admin)',
    uploadedAt: '2026-09-05T12:00:00Z',
    version: '1.4',
    status: 'ACTIVE'
  },
  {
    id: 'wks-3',
    code: 'WKS-WLD-003',
    title: '6G Pipe GTAW Root & SMAW Cap Visual Acceptance Criteria',
    occupation: 'Welding & Fabrication',
    taskId: 'tsk-3',
    fileName: '6G_Pipe_Weld_Inspection_Form.pdf',
    fileSize: '3.1 MB',
    uploadedBy: 'Tariq Al-Mansoor (Super Admin)',
    uploadedAt: '2026-09-02T14:00:00Z',
    version: '3.0',
    status: 'ACTIVE'
  },
  {
    id: 'wks-4',
    code: 'WKS-BMS-004',
    title: 'BACnet MS/TP Loop Commissioning Protocol',
    occupation: 'BMS Automation',
    taskId: 'tsk-4',
    fileName: 'BMS_DDC_Loop_Commissioning_Sheet.pdf',
    fileSize: '1.5 MB',
    uploadedBy: 'Tariq Al-Mansoor (Super Admin)',
    uploadedAt: '2026-09-08T11:00:00Z',
    version: '1.0',
    status: 'ACTIVE'
  },
  {
    id: 'wks-5',
    code: 'WKS-PLM-005',
    title: 'Hydrostatic Pressure Test Verification Log',
    occupation: 'Plumbing',
    taskId: 'tsk-5',
    fileName: 'Plumbing_Pressure_Test_Record.pdf',
    fileSize: '950 KB',
    uploadedBy: 'Tariq Al-Mansoor (Super Admin)',
    uploadedAt: '2026-09-04T09:00:00Z',
    version: '1.2',
    status: 'ACTIVE'
  }
];

export const DEMO_TASK_ALLOCATIONS: TaskAllocation[] = [
  {
    id: 'tal-1',
    candidateId: 'can-1',
    candidateName: 'Mohammed Alamgir Hossain',
    aproReference: 'APRO-SA-92812',
    occupation: 'Electrical Installation',
    taskId: 'tsk-1',
    taskCode: 'TSK-ELE-01',
    taskTitle: 'Three-Phase Motor Control Circuit Wiring & Troubleshooting',
    difficulty: 'INTERMEDIATE',
    assignedDate: '2026-09-17T09:00:00Z',
    status: 'ASSIGNED'
  },
  {
    id: 'tal-2',
    candidateId: 'can-2',
    candidateName: 'Abdul Karim Mansoor',
    aproReference: 'APRO-SA-92813',
    occupation: 'Electrical Installation',
    taskId: 'tsk-1',
    taskCode: 'TSK-ELE-01',
    taskTitle: 'Three-Phase Motor Control Circuit Wiring & Troubleshooting',
    difficulty: 'INTERMEDIATE',
    assignedDate: '2026-09-17T09:00:00Z',
    status: 'ASSIGNED'
  },
  {
    id: 'tal-3',
    candidateId: 'can-3',
    candidateName: 'Shahidul Islam Mia',
    aproReference: 'APRO-SA-92814',
    occupation: 'HVAC Maintenance',
    taskId: 'tsk-2',
    taskCode: 'TSK-HVAC-01',
    taskTitle: 'Split AC Refrigerant Evacuation, Leak Check and Charging',
    difficulty: 'INTERMEDIATE',
    assignedDate: '2026-09-16T10:00:00Z',
    status: 'IN_PROGRESS'
  },
  {
    id: 'tal-4',
    candidateId: 'can-4',
    candidateName: 'Kamal Pasha Rashed',
    aproReference: 'APRO-SA-92815',
    occupation: 'Welding & Fabrication',
    taskId: 'tsk-3',
    taskCode: 'TSK-WLD-01',
    taskTitle: 'TIG 6G Pipe Joint Welding & Visual Defect Inspection',
    difficulty: 'ADVANCED',
    assignedDate: '2026-09-14T08:30:00Z',
    status: 'COMPLETED'
  },
  {
    id: 'tal-5',
    candidateId: 'can-6',
    candidateName: 'Mahfuzur Rahman',
    aproReference: 'APRO-SA-92816',
    occupation: 'Electrical Installation',
    taskId: 'tsk-1',
    taskCode: 'TSK-ELE-01',
    taskTitle: 'Three-Phase Motor Control Circuit Wiring & Troubleshooting',
    difficulty: 'INTERMEDIATE',
    assignedDate: '2026-09-12T09:00:00Z',
    status: 'COMPLETED'
  },
  {
    id: 'tal-6',
    candidateId: 'can-14',
    candidateName: 'Farhan Tariq Al-Bishi',
    aproReference: 'APRO-SA-92819',
    occupation: 'HVAC Maintenance',
    taskId: 'tsk-2',
    taskCode: 'TSK-HVAC-01',
    taskTitle: 'Split AC Refrigerant Evacuation, Leak Check and Charging',
    difficulty: 'INTERMEDIATE',
    assignedDate: '2026-09-11T10:00:00Z',
    status: 'COMPLETED'
  },
  {
    id: 'tal-7',
    candidateId: 'can-16',
    candidateName: 'Bilal Hussain Shah',
    aproReference: 'APRO-SA-92820',
    occupation: 'Welding & Fabrication',
    taskId: 'tsk-3',
    taskCode: 'TSK-WLD-01',
    taskTitle: 'TIG 6G Pipe Joint Welding & Visual Defect Inspection',
    difficulty: 'ADVANCED',
    assignedDate: '2026-09-12T09:00:00Z',
    status: 'COMPLETED'
  }
];

export const DEMO_ASSESSOR_LOTTERY: AssessorLottery[] = [
  {
    id: 'lot-1',
    scheduleId: 'sch-1',
    scheduleCode: 'SCH-2026-091',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    candidateCount: 25,
    eligibleAssessorCount: 2,
    allocationStatus: 'GENERATED',
    releaseStatus: 'RELEASED',
    releaseTime: '2026-09-18T07:00:00Z',
    generatedAt: '2026-09-17T08:00:00Z',
    pairings: [
      {
        candidateId: 'can-1',
        candidateName: 'Mohammed Alamgir Hossain',
        aproReference: 'APRO-SA-92812',
        assessorId: 'usr-4',
        assessorName: 'Eng. Yasir Mahmood'
      },
      {
        candidateId: 'can-2',
        candidateName: 'Abdul Karim Mansoor',
        aproReference: 'APRO-SA-92813',
        assessorId: 'usr-12',
        assessorName: 'Salem Al-Dossary'
      },
      {
        candidateId: 'can-6',
        candidateName: 'Mahfuzur Rahman',
        aproReference: 'APRO-SA-92816',
        assessorId: 'usr-4',
        assessorName: 'Eng. Yasir Mahmood'
      },
      {
        candidateId: 'can-22',
        candidateName: 'Khalid Masood',
        aproReference: 'APRO-SA-92823',
        assessorId: 'usr-12',
        assessorName: 'Salem Al-Dossary'
      }
    ]
  },
  {
    id: 'lot-2',
    scheduleId: 'sch-2',
    scheduleCode: 'SCH-2026-092',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    candidateCount: 18,
    eligibleAssessorCount: 2,
    allocationStatus: 'GENERATED',
    releaseStatus: 'HIDDEN',
    releaseTime: '2026-09-19T12:00:00Z',
    generatedAt: '2026-09-17T09:30:00Z',
    pairings: [
      {
        candidateId: 'can-3',
        candidateName: 'Shahidul Islam Mia',
        aproReference: 'APRO-SA-92814',
        assessorId: 'usr-4',
        assessorName: 'Eng. Yasir Mahmood'
      },
      {
        candidateId: 'can-14',
        candidateName: 'Farhan Tariq Al-Bishi',
        aproReference: 'APRO-SA-92819',
        assessorId: 'usr-12',
        assessorName: 'Salem Al-Dossary'
      },
      {
        candidateId: 'can-21',
        candidateName: 'Saad Abdullah Al-Qarni',
        aproReference: 'APRO-SA-92822',
        assessorId: 'usr-4',
        assessorName: 'Eng. Yasir Mahmood'
      }
    ]
  }
];

export const DEMO_TASK_LOTTERY: TaskLottery[] = [
  {
    id: 'tlot-1',
    candidateId: 'can-1',
    candidateName: 'Mohammed Alamgir Hossain',
    aproReference: 'APRO-SA-92812',
    occupation: 'Electrical Installation',
    taskPoolId: 'pool-ele',
    assignedTaskId: 'tsk-1',
    taskTitle: 'Three-Phase Motor Control Circuit Wiring & Troubleshooting',
    difficulty: 'INTERMEDIATE',
    allocationTime: '2026-09-17T08:15:00Z',
    status: 'CONFIRMED'
  },
  {
    id: 'tlot-2',
    candidateId: 'can-3',
    candidateName: 'Shahidul Islam Mia',
    aproReference: 'APRO-SA-92814',
    occupation: 'HVAC Maintenance',
    taskPoolId: 'pool-hvac',
    assignedTaskId: 'tsk-2',
    taskTitle: 'Split AC Refrigerant Evacuation, Leak Check and Charging',
    difficulty: 'INTERMEDIATE',
    allocationTime: '2026-09-16T09:30:00Z',
    status: 'CONFIRMED'
  },
  {
    id: 'tlot-3',
    candidateId: 'can-4',
    candidateName: 'Kamal Pasha Rashed',
    aproReference: 'APRO-SA-92815',
    occupation: 'Welding & Fabrication',
    taskPoolId: 'pool-wld',
    assignedTaskId: 'tsk-3',
    taskTitle: 'TIG 6G Pipe Joint Welding & Visual Defect Inspection',
    difficulty: 'ADVANCED',
    allocationTime: '2026-09-14T08:00:00Z',
    status: 'CONFIRMED'
  }
];

export const DEMO_ASSESSMENTS: Assessment[] = [
  {
    id: 'asm-1',
    candidateId: 'can-1',
    candidateName: 'Mohammed Alamgir Hossain',
    centerId: 'ctr-sa-1',
    countryId: 'cnt-sa',
    assessorId: 'usr-4',
    assessorName: 'Eng. Yasir Mahmood',
    scheduleId: 'sch-1',
    occupation: 'Electrical Installation',
    date: '2026-09-18',
    status: 'SCHEDULED'
  },
  {
    id: 'asm-2',
    candidateId: 'can-3',
    candidateName: 'Shahidul Islam Mia',
    centerId: 'ctr-sa-1',
    countryId: 'cnt-sa',
    assessorId: 'usr-4',
    assessorName: 'Eng. Yasir Mahmood',
    scheduleId: 'sch-2',
    occupation: 'HVAC Maintenance',
    date: '2026-09-16',
    theoryScore: 84,
    practicalScore: 78,
    totalScore: 81,
    status: 'PRACTICAL_IN_PROGRESS'
  },
  {
    id: 'asm-3',
    candidateId: 'can-4',
    candidateName: 'Kamal Pasha Rashed',
    centerId: 'ctr-sa-2',
    countryId: 'cnt-sa',
    assessorId: 'usr-13',
    assessorName: 'Ibrahim Al-Mutawa',
    scheduleId: 'sch-3',
    occupation: 'Welding & Fabrication',
    date: '2026-09-14',
    theoryScore: 88,
    practicalScore: 85,
    totalScore: 86.5,
    status: 'RESULT_SUBMITTED',
    evaluatedAt: '2026-09-14T14:30:00Z'
  },
  {
    id: 'asm-4',
    candidateId: 'can-6',
    candidateName: 'Mahfuzur Rahman',
    centerId: 'ctr-sa-1',
    countryId: 'cnt-sa',
    assessorId: 'usr-4',
    assessorName: 'Eng. Yasir Mahmood',
    scheduleId: 'sch-1',
    occupation: 'Electrical Installation',
    date: '2026-09-12',
    theoryScore: 92,
    practicalScore: 89,
    totalScore: 90.5,
    status: 'LOCKED',
    evaluatedAt: '2026-09-12T15:00:00Z'
  },
  {
    id: 'asm-5',
    candidateId: 'can-14',
    candidateName: 'Farhan Tariq Al-Bishi',
    centerId: 'ctr-sa-1',
    countryId: 'cnt-sa',
    assessorId: 'usr-4',
    assessorName: 'Eng. Yasir Mahmood',
    scheduleId: 'sch-2',
    occupation: 'HVAC Maintenance',
    date: '2026-09-11',
    theoryScore: 90,
    practicalScore: 86,
    totalScore: 88,
    status: 'LOCKED',
    evaluatedAt: '2026-09-11T16:00:00Z'
  },
  {
    id: 'asm-6',
    candidateId: 'can-16',
    candidateName: 'Bilal Hussain Shah',
    centerId: 'ctr-sa-2',
    countryId: 'cnt-sa',
    assessorId: 'usr-13',
    assessorName: 'Ibrahim Al-Mutawa',
    scheduleId: 'sch-3',
    occupation: 'Welding & Fabrication',
    date: '2026-09-12',
    theoryScore: 68,
    practicalScore: 58,
    totalScore: 63,
    status: 'LOCKED',
    evaluatedAt: '2026-09-12T17:00:00Z'
  }
];

export const DEMO_RESULTS: Result[] = [
  {
    id: 'res-1',
    assessmentId: 'asm-4',
    candidateId: 'can-6',
    candidateName: 'Mahfuzur Rahman',
    aproReference: 'APRO-SA-92816',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    occupation: 'Electrical Installation',
    assessorName: 'Eng. Yasir Mahmood',
    theoryScore: 92,
    practicalScore: 89,
    score: 90.5,
    grade: 'DISTINCTION',
    status: 'LOCKED',
    certificateNumber: 'CERT-SA-2026-00491',
    submissionDate: '2026-09-12T15:00:00Z',
    issuedAt: '2026-09-13T10:00:00Z'
  },
  {
    id: 'res-2',
    assessmentId: 'asm-3',
    candidateId: 'can-4',
    candidateName: 'Kamal Pasha Rashed',
    aproReference: 'APRO-SA-92815',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-2',
    occupation: 'Welding & Fabrication',
    assessorName: 'Ibrahim Al-Mutawa',
    theoryScore: 88,
    practicalScore: 85,
    score: 86.5,
    grade: 'PASS',
    status: 'SUBMITTED',
    submissionDate: '2026-09-14T14:30:00Z'
  },
  {
    id: 'res-3',
    assessmentId: 'asm-5',
    candidateId: 'can-14',
    candidateName: 'Farhan Tariq Al-Bishi',
    aproReference: 'APRO-SA-92819',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    occupation: 'HVAC Maintenance',
    assessorName: 'Eng. Yasir Mahmood',
    theoryScore: 90,
    practicalScore: 86,
    score: 88.0,
    grade: 'PASS',
    status: 'LOCKED',
    certificateNumber: 'CERT-SA-2026-00492',
    submissionDate: '2026-09-11T16:00:00Z',
    issuedAt: '2026-09-12T11:00:00Z'
  },
  {
    id: 'res-4',
    assessmentId: 'asm-6',
    candidateId: 'can-16',
    candidateName: 'Bilal Hussain Shah',
    aproReference: 'APRO-SA-92820',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-2',
    occupation: 'Welding & Fabrication',
    assessorName: 'Ibrahim Al-Mutawa',
    theoryScore: 68,
    practicalScore: 58,
    score: 63.0,
    grade: 'FAIL',
    status: 'CORRECTED',
    submissionDate: '2026-09-12T17:00:00Z',
    correctionHistory: [
      {
        originalScore: 59.0,
        updatedScore: 63.0,
        originalGrade: 'FAIL',
        updatedGrade: 'FAIL',
        reason: 'Administrative recalculation: corrected rubric item 3 scoring error upon supervisory audit review.',
        changedBy: 'Tariq Al-Mansoor (Super Admin)',
        changedAt: '2026-09-13T09:30:00Z'
      }
    ]
  },
  {
    id: 'res-5',
    assessmentId: 'asm-2',
    candidateId: 'can-3',
    candidateName: 'Shahidul Islam Mia',
    aproReference: 'APRO-SA-92814',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    occupation: 'HVAC Maintenance',
    assessorName: 'Eng. Yasir Mahmood',
    theoryScore: 84,
    practicalScore: 78,
    score: 81.0,
    grade: 'PASS',
    status: 'PENDING',
    submissionDate: '2026-09-16T18:00:00Z'
  }
];

export const DEMO_COMPLAINTS: Complaint[] = [
  {
    id: 'cmp-1',
    complaintNumber: 'CMP-2026-001',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    reportedBy: 'Candidate: Mohammed Alamgir Hossain (APRO-SA-92812)',
    category: 'TECHNICAL_EQUIPMENT',
    priority: 'MEDIUM',
    status: 'RESOLVED',
    subject: 'Faulty Digital Multimeter probe during motor wiring test',
    description: 'Lead probe had an intermittent wire disconnect during resistance continuity check. Center support provided replacement meter within 3 minutes.',
    assignedTo: 'usr-3',
    assignedToName: 'Dr. Khalid Al-Zahrani (Center Admin)',
    createdAt: '2026-09-12T10:15:00Z',
    resolvedAt: '2026-09-12T11:00:00Z',
    resolutionNotes: 'Replacement equipment verified by Lead Assessor Eng. Yasir. Additional 10 minutes testing time allotted.',
    history: [
      {
        id: 'cmph-1',
        complaintId: 'cmp-1',
        fromStatus: undefined,
        toStatus: 'OPEN',
        changedBy: 'Mohammed Alamgir Hossain (APRO-SA-92812)',
        changedAt: '2026-09-12T10:15:00Z',
        comment: 'Grievance ticket logged regarding faulty multimeter probe.'
      },
      {
        id: 'cmph-2',
        complaintId: 'cmp-1',
        fromStatus: 'OPEN',
        toStatus: 'UNDER_REVIEW',
        changedBy: 'Dr. Khalid Al-Zahrani',
        changedAt: '2026-09-12T10:25:00Z',
        assignedTo: 'Dr. Khalid Al-Zahrani',
        comment: 'Assigned to Center Admin for workshop inspection.'
      },
      {
        id: 'cmph-3',
        complaintId: 'cmp-1',
        fromStatus: 'UNDER_REVIEW',
        toStatus: 'RESOLVED',
        changedBy: 'Dr. Khalid Al-Zahrani',
        changedAt: '2026-09-12T11:00:00Z',
        comment: 'Replacement calibrated meter issued and verified. Additional practical duration granted.'
      }
    ]
  },
  {
    id: 'cmp-2',
    complaintNumber: 'CMP-2026-002',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-2',
    reportedBy: 'Candidate: Bilal Hussain Shah (APRO-SA-92820)',
    category: 'RESULT_DISPUTE',
    priority: 'HIGH',
    status: 'UNDER_REVIEW',
    subject: 'Request for re-evaluation of pipe weld cap reinforcement scoring',
    description: 'Candidate petitions that undercut score was penalized twice under both root and cover pass rubrics in Welding & Fabrication.',
    assignedTo: 'usr-1',
    assignedToName: 'Tariq Al-Mansoor (Super Admin)',
    createdAt: '2026-09-14T11:00:00Z',
    history: [
      {
        id: 'cmph-4',
        complaintId: 'cmp-2',
        fromStatus: undefined,
        toStatus: 'OPEN',
        changedBy: 'Bilal Hussain Shah (APRO-SA-92820)',
        changedAt: '2026-09-14T11:00:00Z',
        comment: 'Formal appeal submitted regarding double-penalty on practical rubric.'
      },
      {
        id: 'cmph-5',
        complaintId: 'cmp-2',
        fromStatus: 'OPEN',
        toStatus: 'UNDER_REVIEW',
        changedBy: 'Tariq Al-Mansoor',
        changedAt: '2026-09-14T14:30:00Z',
        assignedTo: 'Tariq Al-Mansoor',
        comment: 'Escalated to National Assessment Committee for rubric re-calculation.'
      }
    ]
  },
  {
    id: 'cmp-3',
    complaintNumber: 'CMP-2026-003',
    countryId: 'cnt-ae',
    centerId: 'ctr-ae-1',
    reportedBy: 'Staff: Fatima Al-Zahra',
    category: 'FACILITY',
    priority: 'LOW',
    status: 'ACTION_REQUIRED',
    subject: 'Workshop 2 air extraction blower vibration noise',
    description: 'Ventilation blower fan in electrical lab 2 has mechanical vibration requiring preventative lubrication before next shift.',
    assignedTo: 'usr-center-ae',
    assignedToName: 'Omar Al-Mansouri (Center Admin)',
    createdAt: '2026-09-15T08:30:00Z',
    history: [
      {
        id: 'cmph-6',
        complaintId: 'cmp-3',
        fromStatus: undefined,
        toStatus: 'OPEN',
        changedBy: 'Fatima Al-Zahra',
        changedAt: '2026-09-15T08:30:00Z',
        comment: 'Facility maintenance ticket logged.'
      },
      {
        id: 'cmph-7',
        complaintId: 'cmp-3',
        fromStatus: 'OPEN',
        toStatus: 'ACTION_REQUIRED',
        changedBy: 'Omar Al-Mansouri',
        changedAt: '2026-09-15T09:15:00Z',
        assignedTo: 'Omar Al-Mansouri',
        comment: 'Physical maintenance inspection required by facility engineering team.'
      }
    ]
  },
  {
    id: 'cmp-4',
    complaintNumber: 'CMP-2026-004',
    countryId: 'cnt-bd',
    centerId: 'ctr-bd-1',
    reportedBy: 'Assessor: Kamal Hossain',
    category: 'EXAMINATION_CONDUCT',
    priority: 'URGENT',
    status: 'CLOSED',
    subject: 'Candidate biometric verification system momentary network timeout',
    description: 'Local ISP disruption caused a 4-minute delay in biometric enrollment verification at intake desk.',
    assignedTo: 'usr-center-bd',
    assignedToName: 'Tanvir Mahmud (Center Admin)',
    createdAt: '2026-09-16T09:00:00Z',
    resolvedAt: '2026-09-16T09:20:00Z',
    resolutionNotes: 'Switched immediately to backup 5G secondary link. All candidates authenticated without data loss.',
    history: [
      {
        id: 'cmph-8',
        complaintId: 'cmp-4',
        fromStatus: undefined,
        toStatus: 'OPEN',
        changedBy: 'Kamal Hossain',
        changedAt: '2026-09-16T09:00:00Z',
        comment: 'Network timeout incident reported.'
      },
      {
        id: 'cmph-9',
        complaintId: 'cmp-4',
        fromStatus: 'OPEN',
        toStatus: 'RESOLVED',
        changedBy: 'Tanvir Mahmud',
        changedAt: '2026-09-16T09:15:00Z',
        comment: 'Backup cellular link engaged successfully.'
      },
      {
        id: 'cmph-10',
        complaintId: 'cmp-4',
        fromStatus: 'RESOLVED',
        toStatus: 'CLOSED',
        changedBy: 'Tanvir Mahmud',
        changedAt: '2026-09-16T09:20:00Z',
        comment: 'Incident settled and closed with zero data discrepancy.'
      }
    ]
  },
  {
    id: 'cmp-5',
    complaintNumber: 'CMP-2026-005',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    reportedBy: 'Candidate: Abdul Karim Mansoor (APRO-SA-92813)',
    category: 'EXAMINATION_CONDUCT',
    priority: 'MEDIUM',
    status: 'OPEN',
    subject: 'Clarification requested on bay safety isolation switch tagging procedure',
    description: 'Candidate inquires whether bay circuit isolation should have been tagged before or after distribution bar de-energization.',
    createdAt: '2026-09-18T09:10:00Z',
    history: [
      {
        id: 'cmph-11',
        complaintId: 'cmp-5',
        fromStatus: undefined,
        toStatus: 'OPEN',
        changedBy: 'Abdul Karim Mansoor',
        changedAt: '2026-09-18T09:10:00Z',
        comment: 'Candidate inquiry logged at reception desk.'
      }
    ]
  }
];

export const DEMO_LIVE_ACTIVITY: LiveActivityEvent[] = [
  {
    id: 'act-1',
    timestamp: '2026-09-17T08:45:00Z',
    countryId: 'cnt-sa',
    countryName: 'Saudi Arabia',
    centerId: 'ctr-sa-1',
    centerName: 'Riyadh Central Technical Hub',
    user: 'Maryam Al-Shehri',
    role: 'SUPPORT_STAFF',
    action: 'CANDIDATE_ENROLLED',
    entity: 'Mohammed Alamgir Hossain (APRO-SA-92812)',
    status: 'SUCCESS'
  },
  {
    id: 'act-2',
    timestamp: '2026-09-17T08:30:00Z',
    countryId: 'cnt-sa',
    countryName: 'Saudi Arabia',
    centerId: 'ctr-sa-1',
    centerName: 'Riyadh Central Technical Hub',
    user: 'Eng. Yasir Mahmood',
    role: 'ASSESSOR',
    action: 'ASSESSMENT_STARTED',
    entity: 'Electrical Installation - Batch 081',
    status: 'INFO'
  },
  {
    id: 'act-3',
    timestamp: '2026-09-17T08:15:00Z',
    countryId: 'cnt-sa',
    countryName: 'Saudi Arabia',
    centerId: 'ctr-sa-1',
    centerName: 'Riyadh Central Technical Hub',
    user: 'System Engine',
    role: 'SUPER_ADMIN',
    action: 'PRACTICAL_TASK_ALLOCATED',
    entity: 'Task TSK-ELE-01 auto-assigned to Candidate can-1',
    status: 'SUCCESS'
  },
  {
    id: 'act-4',
    timestamp: '2026-09-17T07:50:00Z',
    countryId: 'cnt-ae',
    countryName: 'United Arab Emirates',
    centerId: 'ctr-ae-1',
    centerName: 'Dubai Skill Excellence Campus',
    user: 'Omar Al-Mansouri',
    role: 'CENTER_ADMIN',
    action: 'BATCH_PREPARED',
    entity: 'BATCH-2026-084 for BMS Automation',
    status: 'INFO'
  },
  {
    id: 'act-5',
    timestamp: '2026-09-16T16:30:00Z',
    countryId: 'cnt-sa',
    countryName: 'Saudi Arabia',
    centerId: 'ctr-sa-2',
    centerName: 'Jeddah Coastal Vocational Center',
    user: 'Ibrahim Al-Mutawa',
    role: 'ASSESSOR',
    action: 'RESULT_SUBMITTED',
    entity: 'Candidate Kamal Pasha (APRO-SA-92815) - Score: 86.5%',
    status: 'SUCCESS'
  },
  {
    id: 'act-6',
    timestamp: '2026-09-16T14:15:00Z',
    countryId: 'cnt-sa',
    countryName: 'Saudi Arabia',
    centerId: 'ctr-sa-1',
    centerName: 'Riyadh Central Technical Hub',
    user: 'Tariq Al-Mansoor',
    role: 'SUPER_ADMIN',
    action: 'RESULT_CORRECTED',
    entity: 'Administrative Score Update for APRO-SA-92820',
    status: 'WARNING'
  }
];

export const DEMO_APRO_CONFIG: APROConfig = {
  format: '{PREFIX}-{COUNTRY_CODE}-{SEQUENCE_NUM}',
  prefix: 'APRO',
  sequence: 92824,
  sampleGenerated: 'APRO-SA-092824',
  status: 'ACTIVE',
  isConfigurable: true,
  note: 'Assessment reference identifier format (Configurable / TBC pending final regulatory ratification).'
};

export const DEMO_SERIAL_CONFIG: SerialConfig = {
  prefix: 'CERT',
  startingNumber: 10001,
  currentNumber: 10493,
  format: 'CERT-{COUNTRY}-{YEAR}-{NUMBER:5}',
  status: 'ACTIVE',
  note: 'Serial tracking for digital competency certificates (Configurable / TBC).'
};

export const DEMO_ASSESSMENT_SETTINGS: AssessmentSettingsConfig = {
  cbtDurationMinutes: 60,
  practicalDurationMinutes: 120,
  assignmentReleaseHoursBefore: 2,
  passingScorePercentage: 70,
  practicalWeightPercentage: 60,
  allowResultCorrection: true,
  lockTimeoutMinutes: 1440,
  blindLotteryEnforced: true
};

export const DEMO_IDCARD_CONFIG: IDCardConfig = {
  templateName: 'Standard National Security Skill Card (ISO/IEC 7810 ID-1)',
  showQrCode: true,
  showPassport: true,
  showApro: true,
  primaryColor: '#7A2E3A',
  issueAuthority: 'SkillAssess 360 National Skill Verification Directorate',
  status: 'ACTIVE'
};

export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    titleEn: 'New Center Registered',
    titleAr: 'تم تسجيل مركز تقييم جديد',
    messageEn: 'Riyadh Central Technical Hub has been verified and active.',
    messageAr: 'تم التحقق من مركز الرياض الرئيسي للتقييم التقني وتفعيله بنجاح.',
    type: 'SUCCESS',
    targetRole: 'SUPER_ADMIN',
    read: false,
    createdAt: '2026-09-17T08:00:00Z',
    link: '/centers'
  },
  {
    id: 'notif-2',
    titleEn: 'Candidate-Assessor Lottery Release Pending',
    titleAr: 'إطلاق قرعة المقيمين والمرشحين معلق',
    messageEn: 'Schedule SCH-2026-092 blind allocation is generated and will unlock at 12:00 UTC.',
    messageAr: 'تم توليد التخصيص الأعمى للجدول SCH-2026-092 وسيتم إطلاقه في 12:00 بالتوقيت المعتمد.',
    type: 'INFO',
    targetRole: 'SUPER_ADMIN',
    read: false,
    createdAt: '2026-09-17T07:30:00Z',
    link: '/lottery/assessor'
  },
  {
    id: 'notif-3',
    titleEn: 'Result Correction Recorded',
    titleAr: 'تم تسجيل تصحيح إداري لنتيجة',
    messageEn: 'Super Admin executed administrative correction for candidate APRO-SA-92820.',
    messageAr: 'أجرى المشرف العام تعديلاً إدارياً رسمياً لنتيجة المرشح APRO-SA-92820.',
    type: 'WARNING',
    targetRole: 'SUPER_ADMIN',
    read: false,
    createdAt: '2026-09-16T14:15:00Z',
    link: '/results'
  },
  {
    id: 'notif-4',
    titleEn: 'Batch Capacity Alert',
    titleAr: 'تنبيه سعة الدفعة',
    messageEn: 'BATCH-2026-081 is at 100% seating capacity.',
    messageAr: 'الدفعة BATCH-2026-081 وصلت إلى طاقتها الاستيعابية الكاملة (100%).',
    type: 'WARNING',
    targetRole: 'ALL',
    read: true,
    createdAt: '2026-09-15T15:45:00Z',
    link: '/batches'
  },
  {
    id: 'notif-5',
    titleEn: 'Security Audit Notice',
    titleAr: 'إشعار التدقيق الأمني',
    messageEn: 'Quarterly compliance audit trail exported successfully.',
    messageAr: 'تم تصدير سجل التدقيق الفصلي للامتثال بنجاح.',
    type: 'ALERT',
    targetRole: 'SUPER_ADMIN',
    read: true,
    createdAt: '2026-09-15T08:00:00Z',
    link: '/audit'
  },
  {
    id: 'notif-6',
    titleEn: 'Biometric Photo Quality Flag',
    titleAr: 'تنبيه جودة الصورة البيومترية للمرشح',
    messageEn: 'Candidate Khalid Al-Otaibi (P8819201) portrait flagged for glare recalibration. Please verify in Photos gallery.',
    messageAr: 'صورة المرشح خالد العتيبي (P8819201) بحاجة لإعادة التحقق بسبب وهج الإضاءة. يرجى مراجعة قسم الصور.',
    type: 'WARNING',
    targetRole: 'SUPPORT_STAFF',
    read: false,
    createdAt: '2026-09-17T07:15:00Z',
    link: '/candidate-photos'
  },
  {
    id: 'notif-7',
    titleEn: 'Batch BATCH-2026-081 Intake Commenced',
    titleAr: 'بدء استقبال دفعة التقييم BATCH-2026-081',
    messageEn: 'Shift 1 candidate reception has commenced at Hub A. 25 candidates expected for Electrical Installation verification.',
    messageAr: 'بدأ استقبال المرشحين للوردية الأولى في الصالة A. متوقع حضور 25 مرشحاً للتحقق من الهوية.',
    type: 'INFO',
    targetRole: 'SUPPORT_STAFF',
    read: false,
    createdAt: '2026-09-17T06:50:00Z',
    link: '/batches'
  },
  {
    id: 'notif-8',
    titleEn: 'Candidate Identification Verified',
    titleAr: 'اكتمال التحقق من هوية المرشح',
    messageEn: 'Candidate Tariq Al-Amri (APRO-SA-92812) biometric match confirmed at Reception desk.',
    messageAr: 'تم تأكيد المطابقة البيومترية للمرشح طارق العمري (APRO-SA-92812) في مكتب الاستقبال.',
    type: 'SUCCESS',
    targetRole: 'SUPPORT_STAFF',
    read: true,
    createdAt: '2026-09-17T06:30:00Z',
    link: '/candidates'
  }
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    userId: 'usr-1',
    userName: 'Tariq Al-Mansoor',
    role: 'SUPER_ADMIN',
    action: 'LOGIN',
    entity: 'AUTH',
    details: 'Super Admin authenticated from secure headquarters workstation.',
    ipAddress: '10.0.4.12',
    deviceInfo: 'Primary Oversight Console (Dell Precision 5820)',
    browserInfo: 'Enterprise Kiosk Browser v124',
    osInfo: 'Windows 11 Enterprise (ISO SECURE)',
    timestamp: '2026-09-17T08:30:00Z',
    status: 'SUCCESS'
  },
  {
    id: 'aud-2',
    userId: 'usr-1',
    userName: 'Tariq Al-Mansoor',
    role: 'SUPER_ADMIN',
    countryId: 'cnt-sa',
    action: 'CREATE_COUNTRY',
    entity: 'COUNTRY',
    entityId: 'cnt-sa',
    details: 'Created Country Authority for Saudi Arabia (SA).',
    ipAddress: '10.0.4.12',
    deviceInfo: 'Primary Oversight Console',
    browserInfo: 'Enterprise Kiosk Browser v124',
    osInfo: 'Windows 11 Enterprise',
    timestamp: '2026-09-15T10:00:00Z',
    status: 'SUCCESS'
  },
  {
    id: 'aud-3',
    userId: 'usr-1',
    userName: 'Tariq Al-Mansoor',
    role: 'SUPER_ADMIN',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    action: 'CREATE_CENTER',
    entity: 'CENTER',
    entityId: 'ctr-sa-1',
    details: 'Registered Riyadh Central Technical Hub with capacity 120.',
    ipAddress: '10.0.4.12',
    deviceInfo: 'Primary Oversight Console',
    browserInfo: 'Enterprise Kiosk Browser v124',
    osInfo: 'Windows 11 Enterprise',
    timestamp: '2026-09-15T10:30:00Z',
    status: 'SUCCESS'
  },
  {
    id: 'aud-4',
    userId: 'usr-1',
    userName: 'Tariq Al-Mansoor',
    role: 'SUPER_ADMIN',
    countryId: 'cnt-sa',
    action: 'CREATE_USER',
    entity: 'USER',
    entityId: 'usr-2',
    details: 'Created Country Account for Fahad Al-Otaibi (country.sa).',
    ipAddress: '10.0.4.12',
    deviceInfo: 'Primary Oversight Console',
    browserInfo: 'Enterprise Kiosk Browser v124',
    osInfo: 'Windows 11 Enterprise',
    timestamp: '2026-09-15T11:00:00Z',
    status: 'SUCCESS'
  },
  {
    id: 'aud-5',
    userId: 'usr-1',
    userName: 'Tariq Al-Mansoor',
    role: 'SUPER_ADMIN',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    action: 'CREATE_USER',
    entity: 'USER',
    entityId: 'usr-3',
    details: 'Created Center Admin Dr. Khalid Al-Zahrani for Riyadh Central Hub.',
    ipAddress: '10.0.4.12',
    deviceInfo: 'Primary Oversight Console',
    browserInfo: 'Enterprise Kiosk Browser v124',
    osInfo: 'Windows 11 Enterprise',
    timestamp: '2026-09-15T11:30:00Z',
    status: 'SUCCESS'
  },
  {
    id: 'aud-6',
    userId: 'usr-1',
    userName: 'Tariq Al-Mansoor',
    role: 'SUPER_ADMIN',
    action: 'CREATE_TASK',
    entity: 'PRACTICAL_TASK',
    entityId: 'tsk-1',
    details: 'Configured standardized task TSK-ELE-01 for Electrical Installation.',
    ipAddress: '10.0.4.12',
    deviceInfo: 'Primary Oversight Console',
    browserInfo: 'Enterprise Kiosk Browser v124',
    osInfo: 'Windows 11 Enterprise',
    timestamp: '2026-09-16T08:00:00Z',
    status: 'SUCCESS'
  },
  {
    id: 'aud-7',
    userId: 'usr-1',
    userName: 'Tariq Al-Mansoor',
    role: 'SUPER_ADMIN',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    action: 'GENERATE_LOTTERY',
    entity: 'ASSESSOR_LOTTERY',
    entityId: 'lot-1',
    details: 'Executed blind randomized assessor lottery for Schedule SCH-2026-091.',
    ipAddress: '10.0.4.12',
    deviceInfo: 'Primary Oversight Console',
    browserInfo: 'Enterprise Kiosk Browser v124',
    osInfo: 'Windows 11 Enterprise',
    timestamp: '2026-09-17T08:00:00Z',
    status: 'SUCCESS'
  },
  {
    id: 'aud-8',
    userId: 'usr-1',
    userName: 'Tariq Al-Mansoor',
    role: 'SUPER_ADMIN',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-2',
    action: 'CORRECT_RESULT',
    entity: 'RESULT',
    entityId: 'res-4',
    details: 'Corrected evaluation score from 59.0 to 63.0 for candidate APRO-SA-92820. Reason: rubric item 3 double-penalty recalculation.',
    ipAddress: '10.0.4.12',
    deviceInfo: 'Primary Oversight Console',
    browserInfo: 'Enterprise Kiosk Browser v124',
    osInfo: 'Windows 11 Enterprise',
    timestamp: '2026-09-16T14:15:00Z',
    status: 'SUCCESS'
  },
  {
    id: 'aud-9',
    userId: 'usr-4',
    userName: 'Eng. Yasir Mahmood',
    role: 'ASSESSOR',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    action: 'LOCK',
    entity: 'EVALUATION_RATING',
    entityId: 'rat-1',
    details: 'Submitted and sealed digital evaluation rubric for Tariq Mahmood (APRO-SA-92812). Score: 92.0% (DISTINCTION).',
    ipAddress: '192.168.1.45',
    deviceInfo: 'Assessor Mobile Rugged Tablet (Panasonic Toughbook)',
    browserInfo: 'Secure Assessor Kiosk Agent v4.1',
    osInfo: 'Android 13 Enterprise Security',
    timestamp: '2026-09-18T12:45:00Z',
    status: 'SUCCESS'
  },
  {
    id: 'aud-10',
    userId: 'usr-3',
    userName: 'Dr. Khalid Al-Zahrani',
    role: 'CENTER_ADMIN',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    action: 'UPDATE_COMPLAINT',
    entity: 'COMPLAINT',
    entityId: 'cmp-1',
    details: 'Resolved equipment grievance ticket CMP-2026-001. Replacement multimeter issued to candidate.',
    ipAddress: '192.168.1.10',
    deviceInfo: 'Center Administrative Workstation',
    browserInfo: 'Google Chrome v124.0.6',
    osInfo: 'Windows 11 Pro',
    timestamp: '2026-09-12T11:00:00Z',
    status: 'SUCCESS'
  },
  {
    id: 'aud-11',
    userId: 'usr-6',
    userName: 'Maryam Al-Shehri',
    role: 'SUPPORT_STAFF',
    countryId: 'cnt-sa',
    centerId: 'ctr-sa-1',
    action: 'ENROLL_CANDIDATE',
    entity: 'CANDIDATE',
    entityId: 'can-1',
    details: 'Biometric identification verified and intake dossier sealed for Mohammed Alamgir Hossain (APRO-SA-92812).',
    ipAddress: '192.168.1.22',
    deviceInfo: 'Biometric Intake Scanner Workstation',
    browserInfo: 'SecuGen Biometric Portal Kiosk',
    osInfo: 'Windows 10 Enterprise LTSC',
    timestamp: '2026-09-17T08:45:00Z',
    status: 'SUCCESS'
  }
];

export const DEMO_RESERVATIONS: Reservation[] = [
  {
    id: 'res-sa-101',
    reservationId: 'RES-2026-SA-1001',
    passportNumber: 'EB0982714',
    candidateName: 'Mohammed Alamgir Hossain',
    occupation: 'Electrical Installation',
    status: 'ENROLLED',
    centerId: 'ctr-sa-1',
    batchId: 'bat-1',
    countryId: 'cnt-sa',
    notes: 'Verified biometric visa reservation',
    importedAt: '2026-09-10T07:30:00Z'
  },
  {
    id: 'res-sa-102',
    reservationId: 'RES-2026-SA-1002',
    passportNumber: 'FA8872190',
    candidateName: 'Abdul Karim Mansoor',
    occupation: 'Electrical Installation',
    status: 'PRELOADED',
    centerId: 'ctr-sa-1',
    batchId: 'bat-1',
    countryId: 'cnt-sa',
    notes: 'Preloaded for scheduled cohort batch',
    importedAt: '2026-09-10T07:30:00Z'
  },
  {
    id: 'res-sa-103',
    reservationId: 'RES-2026-SA-1003',
    passportNumber: 'BL7329188',
    candidateName: 'Shahidul Islam Mia',
    occupation: 'HVAC Maintenance',
    status: 'ENROLLED',
    centerId: 'ctr-sa-1',
    batchId: 'bat-2',
    countryId: 'cnt-sa',
    notes: 'Standard technical voucher',
    importedAt: '2026-09-11T08:00:00Z'
  },
  {
    id: 'res-sa-104',
    reservationId: 'RES-2026-SA-1004',
    passportNumber: 'SA1092834',
    candidateName: 'Nasser Saeed Al-Ghamdi',
    occupation: 'Automotive Diagnostics',
    status: 'VALID',
    centerId: 'ctr-sa-1',
    countryId: 'cnt-sa',
    notes: 'Valid agency booking ready for preloading',
    importedAt: '2026-09-12T09:00:00Z'
  },
  {
    id: 'res-sa-105',
    reservationId: 'RES-2026-SA-1005',
    passportNumber: 'SA7719284',
    candidateName: 'Farhan Tariq Al-Bishi',
    occupation: 'HVAC Maintenance',
    status: 'ENROLLED',
    centerId: 'ctr-sa-1',
    batchId: 'bat-2',
    countryId: 'cnt-sa',
    notes: 'Confirmed assessment booking',
    importedAt: '2026-09-11T09:30:00Z'
  },
  {
    id: 'res-sa-106',
    reservationId: 'RES-2026-SA-1006',
    passportNumber: 'SA5591028',
    candidateName: 'Faisal Mohammed Al-Otaibi',
    occupation: 'Electrical Installation',
    status: 'CANCELLED',
    centerId: 'ctr-sa-1',
    countryId: 'cnt-sa',
    notes: 'Cancelled due to employer recall notice',
    importedAt: '2026-09-10T11:00:00Z'
  },
  {
    id: 'res-sa-107',
    reservationId: 'RES-2026-SA-1007',
    passportNumber: 'SA1190284',
    candidateName: 'Saad Abdullah Al-Qarni',
    occupation: 'HVAC Maintenance',
    status: 'VALID',
    centerId: 'ctr-sa-1',
    batchId: 'bat-2',
    countryId: 'cnt-sa',
    notes: 'Ready for batch assignment and preload',
    importedAt: '2026-09-11T11:00:00Z'
  },
  {
    id: 'res-sa-108',
    reservationId: 'RES-2026-SA-1008',
    passportNumber: 'PK7719203',
    candidateName: 'Khalid Masood',
    occupation: 'Plumbing',
    status: 'VALID',
    centerId: 'ctr-sa-1',
    countryId: 'cnt-sa',
    notes: 'Eligible for preloading into upcoming plumbing cycle',
    importedAt: '2026-09-12T13:00:00Z'
  },
  {
    id: 'res-sa-201',
    reservationId: 'RES-2026-SA-2001',
    passportNumber: 'EG4190822',
    candidateName: 'Kamal Pasha Rashed',
    occupation: 'Welding & Fabrication',
    status: 'ENROLLED',
    centerId: 'ctr-sa-2',
    batchId: 'bat-3',
    countryId: 'cnt-sa',
    notes: 'Jeddah Hub registered reservation',
    importedAt: '2026-09-12T09:30:00Z'
  },
  {
    id: 'res-sa-202',
    reservationId: 'RES-2026-SA-2002',
    passportNumber: 'PK8819203',
    candidateName: 'Bilal Hussain Shah',
    occupation: 'Welding & Fabrication',
    status: 'ENROLLED',
    centerId: 'ctr-sa-2',
    batchId: 'bat-3',
    countryId: 'cnt-sa',
    notes: 'SMAW qualification reservation',
    importedAt: '2026-09-12T10:30:00Z'
  }
];

export const DEFAULT_EVALUATION_RUBRIC: EvaluationRubricSection[] = [
  {
    id: 'sec-1',
    code: 'PROB_DEMO',
    titleEn: 'Problem Understanding & Demo Process Flow',
    titleAr: 'فهم المسألة ومسار العرض العملي',
    weightPercentage: 25,
    questions: [
      { id: 'q1-1', code: 'Q1', textEn: 'Demonstrates clear interpretation of schematic drawings and technical blueprints.', textAr: 'يُظهر فهماً وتفسيراً دقيقاً للمخططات الفنية والتصاميم الهندسية.', maxScore: 5 },
      { id: 'q1-2', code: 'Q2', textEn: 'Explains proper operational sequencing before beginning practical work.', textAr: 'يشرح التسلسل التشغيلي الصحيح بوضوح قبل بدء العمل العملي.', maxScore: 5 },
      { id: 'q1-3', code: 'Q3', textEn: 'Selects appropriate materials according to technical specification limits.', textAr: 'يختار المواد المناسبة وفقاً لمتطلبات المواصفات الفنية المحددة.', maxScore: 5 },
      { id: 'q1-4', code: 'Q4', textEn: 'Follows structured execution steps without missing mandatory checkpoints.', textAr: 'يلتزم بخطوات التنفيذ المنهجية دون تجاوز نقاط التحقق الإلزامية.', maxScore: 5 },
      { id: 'q1-5', code: 'Q5', textEn: 'Verifies final assembly alignment and dimensional tolerances accurately.', textAr: 'يتحقق من محاذاة التجميع النهائي والأبعاد الهندسية المسموحة بدقة.', maxScore: 5 },
    ]
  },
  {
    id: 'sec-2',
    code: 'SAFETY',
    titleEn: 'Safety & PPE Compliance',
    titleAr: 'السلامة والامتثال لمعدات الوقاية الشخصية',
    weightPercentage: 25,
    questions: [
      { id: 'q2-1', code: 'Q1', textEn: 'Proper donning and continuous usage of required PPE (helmet, glasses, gloves, boots).', textAr: 'ارتداء واستخدام معدات الوقاية الشخصية الإلزامية طوال فترة التقييم.', maxScore: 5 },
      { id: 'q2-2', code: 'Q2', textEn: 'Demonstrates isolation and lockout/tagout (LOTO) protocols correctly.', textAr: 'يطبق إجراءات العزل وقفل وتأمين مصادر الطاقة بشكل صحيح.', maxScore: 5 },
      { id: 'q2-3', code: 'Q3', textEn: 'Maintains situational hazard awareness and avoids dangerous working positions.', textAr: 'يحافظ على الوعي بالمخاطر المحيطة ويتجنب الوضعيات الخطرة أثناء العمل.', maxScore: 5 },
      { id: 'q2-4', code: 'Q4', textEn: 'Knows location and usage of emergency stops, eyewash stations, and fire extinguishers.', textAr: 'يعرف مواقع واستخدام أزرار الطوارئ ومحطات غسيل الأعين وطفايات الحريق.', maxScore: 5 },
    ]
  },
  {
    id: 'sec-3',
    code: 'TOOLS_EQUIP',
    titleEn: 'Tools & Equipment Setup',
    titleAr: 'تجهيز واستخدام الأدوات والمعدات',
    weightPercentage: 20,
    questions: [
      { id: 'q3-1', code: 'Q1', textEn: 'Pre-inspects tools for physical integrity, wear, and proper electrical insulation.', textAr: 'يفحص الأدوات قبل الاستخدام للتأكد من سلامتها وخلوها من التلف وعزلها.', maxScore: 5 },
      { id: 'q3-2', code: 'Q2', textEn: 'Operates specialized power tools and test instruments strictly within rating limits.', textAr: 'يشغل الأدوات والمعدات الفاحصة بدقة وبما يتوافق مع حدود التشغيل المعتمدة.', maxScore: 5 },
    ]
  },
  {
    id: 'sec-4',
    code: 'HYGIENE',
    titleEn: 'Hygiene & Cleanliness',
    titleAr: 'النظافة والترتيب المهني',
    weightPercentage: 15,
    questions: [
      { id: 'q4-1', code: 'Q1', textEn: 'Maintains an orderly, trip-free workstation throughout practical execution.', textAr: 'يحافظ على تنظيم ونظافة مساحة العمل وخلوها من العوائق أثناء التنفيذ.', maxScore: 5 },
      { id: 'q4-2', code: 'Q2', textEn: 'Disposes of scrap metal, swarf, cable offcuts, and chemical waste into designated bins.', textAr: 'يتخلص من المخلفات المعدنية وقطع الكابلات والنفايات في الحاويات المخصصة.', maxScore: 5 },
    ]
  },
  {
    id: 'sec-5',
    code: 'GENERAL',
    titleEn: 'General Workmanship & Standards',
    titleAr: 'جودة المصنعية والالتزام بالمعايير',
    weightPercentage: 15,
    questions: [
      { id: 'q5-1', code: 'Q1', textEn: 'Completes practical tasks within allotted time limit with professional efficiency.', textAr: 'يتمم المهمة العملية ضمن الوقت المحدد بكفاءة واحترافية عالية.', maxScore: 5 },
      { id: 'q5-2', code: 'Q2', textEn: 'Professional conduct, responsiveness to assessor prompts, and workshop etiquette.', textAr: 'الانضباط المهني والاستجابة لتوجيهات المقيم والالتزام بآداب الورشة.', maxScore: 5 },
    ]
  }
];

export const DEMO_EVALUATION_RATINGS: CandidateEvaluationRating[] = [
  {
    id: 'rat-1',
    candidateId: 'can-6',
    assessorId: 'usr-4',
    assessmentId: 'asm-1',
    batchId: 'bat-1',
    taskId: 'tsk-1',
    taskTitle: 'Three-Phase Distribution Board & Circuit Protection Installation',
    difficulty: 'Moderate',
    ratings: {
      'q1-1': 5, 'q1-2': 5, 'q1-3': 4, 'q1-4': 5, 'q1-5': 4,
      'q2-1': 5, 'q2-2': 5, 'q2-3': 4, 'q2-4': 5,
      'q3-1': 5, 'q3-2': 4,
      'q4-1': 4, 'q4-2': 5,
      'q5-1': 4, 'q5-2': 5
    },
    sectionScores: {
      'sec-1': { score: 23, maxScore: 25, percentage: 92 },
      'sec-2': { score: 19, maxScore: 20, percentage: 95 },
      'sec-3': { score: 9, maxScore: 10, percentage: 90 },
      'sec-4': { score: 9, maxScore: 10, percentage: 90 },
      'sec-5': { score: 9, maxScore: 10, percentage: 90 },
    },
    totalScore: 69,
    totalMaxScore: 75,
    totalPercentage: 92,
    evaluationSheetUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&auto=format&fit=crop&q=80',
    evaluationSheetName: 'EVAL_CAN-6_SEALED.pdf',
    evaluationSheetUploadedAt: '2026-09-18T12:30:00Z',
    assessorRemarks: 'Candidate displayed exemplary wiring neatness, accurate ferrule labeling, and robust safety adherence.',
    status: 'LOCKED',
    submittedAt: '2026-09-18T12:45:00Z',
    lockedAt: '2026-09-18T12:45:00Z'
  }
];

export const DEMO_EVALUATION_SHEETS: EvaluationSheet[] = [
  {
    id: 'sheet-1',
    candidateId: 'can-6',
    assessmentId: 'asm-1',
    assessorId: 'usr-4',
    batchId: 'bat-1',
    fileName: 'EVAL_CAN-6_SEALED.pdf',
    fileSize: '1.4 MB',
    fileUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&auto=format&fit=crop&q=80',
    fileType: 'PDF',
    uploadedAt: '2026-09-18T12:30:00Z'
  }
];

export const DEMO_VARIANCE_RECORDS: AssessmentVarianceRecord[] = [
  {
    id: 'var-1',
    candidateId: 'can-6',
    candidateName: 'Mahfuzur Rahman',
    aproReference: 'APRO-SA-92816',
    assessorId: 'usr-4',
    assessorName: 'Eng. Yasir Mahmood',
    centerId: 'ctr-sa-1',
    centerName: 'Riyadh Central Technical Hub',
    occupation: 'Electrical Installation',
    taskCode: 'TSK-ELE-001',
    taskTitle: 'Three-Phase Distribution Board & Circuit Protection Installation',
    candidateScore: 89,
    cohortAverage: 83.4,
    variance: 5.6,
    riskStatus: 'NORMAL',
    sectionScores: {
      'sec-1': { score: 23, maxScore: 25, percentage: 92 },
      'sec-2': { score: 19, maxScore: 20, percentage: 95 },
      'sec-3': { score: 9, maxScore: 10, percentage: 90 },
      'sec-4': { score: 9, maxScore: 10, percentage: 90 },
      'sec-5': { score: 9, maxScore: 10, percentage: 90 }
    },
    evaluatedAt: '2026-09-18T12:45:00Z'
  },
  {
    id: 'var-2',
    candidateId: 'can-4',
    candidateName: 'Kamal Pasha Rashed',
    aproReference: 'APRO-SA-92815',
    assessorId: 'usr-8',
    assessorName: 'Ibrahim Al-Mutawa',
    centerId: 'ctr-sa-2',
    centerName: 'Jeddah International Testing Facility',
    occupation: 'Welding & Fabrication',
    taskCode: 'TSK-WLD-001',
    taskTitle: 'SMAW 3G Multi-Pass Butt Joint Welding with Visual Inspection',
    candidateScore: 66,
    cohortAverage: 84.1,
    variance: -18.1,
    riskStatus: 'REVIEW_REQUIRED',
    sectionScores: {
      'sec-1': { score: 15, maxScore: 25, percentage: 60 },
      'sec-2': { score: 14, maxScore: 20, percentage: 70 },
      'sec-3': { score: 7, maxScore: 10, percentage: 70 },
      'sec-4': { score: 6, maxScore: 10, percentage: 60 },
      'sec-5': { score: 7, maxScore: 10, percentage: 70 }
    },
    evaluatedAt: '2026-09-17T14:15:00Z'
  },
  {
    id: 'var-3',
    candidateId: 'can-14',
    candidateName: 'Farhan Tariq Al-Bishi',
    aproReference: 'APRO-SA-92819',
    assessorId: 'usr-4',
    assessorName: 'Eng. Yasir Mahmood',
    centerId: 'ctr-sa-1',
    centerName: 'Riyadh Central Technical Hub',
    occupation: 'HVAC Maintenance',
    taskCode: 'TSK-HVC-001',
    taskTitle: 'Refrigerant Recovery, System Evacuation & Deep Vacuum Holding',
    candidateScore: 97,
    cohortAverage: 79.2,
    variance: 17.8,
    riskStatus: 'REVIEW_REQUIRED',
    sectionScores: {
      'sec-1': { score: 25, maxScore: 25, percentage: 100 },
      'sec-2': { score: 20, maxScore: 20, percentage: 100 },
      'sec-3': { score: 10, maxScore: 10, percentage: 100 },
      'sec-4': { score: 9, maxScore: 10, percentage: 90 },
      'sec-5': { score: 10, maxScore: 10, percentage: 100 }
    },
    evaluatedAt: '2026-09-17T11:20:00Z'
  },
  {
    id: 'var-4',
    candidateId: 'can-1',
    candidateName: 'Anowar Hossain',
    aproReference: 'APRO-SA-92811',
    assessorId: 'usr-8',
    assessorName: 'Ibrahim Al-Mutawa',
    centerId: 'ctr-sa-1',
    centerName: 'Riyadh Central Technical Hub',
    occupation: 'Automotive Mechanics',
    taskCode: 'TSK-AUT-001',
    taskTitle: 'OBD-II Diagnostic Troubleshooting & Sensor Testing',
    candidateScore: 82,
    cohortAverage: 80.5,
    variance: 1.5,
    riskStatus: 'NORMAL',
    sectionScores: {
      'sec-1': { score: 21, maxScore: 25, percentage: 84 },
      'sec-2': { score: 16, maxScore: 20, percentage: 80 },
      'sec-3': { score: 8, maxScore: 10, percentage: 80 },
      'sec-4': { score: 8, maxScore: 10, percentage: 80 },
      'sec-5': { score: 8, maxScore: 10, percentage: 80 }
    },
    evaluatedAt: '2026-09-16T16:00:00Z'
  },
  {
    id: 'var-5',
    candidateId: 'can-2',
    candidateName: 'Md Rafiqul Islam',
    aproReference: 'APRO-SA-92812',
    assessorId: 'usr-11',
    assessorName: 'Tariq Al-Juhani',
    centerId: 'ctr-sa-3',
    centerName: 'Dammam Industrial Assessment Complex',
    occupation: 'Electrical Installation',
    taskCode: 'TSK-ELE-001',
    taskTitle: 'Three-Phase Distribution Board & Circuit Protection Installation',
    candidateScore: 71,
    cohortAverage: 83.4,
    variance: -12.4,
    riskStatus: 'ATTENTION',
    sectionScores: {
      'sec-1': { score: 18, maxScore: 25, percentage: 72 },
      'sec-2': { score: 14, maxScore: 20, percentage: 70 },
      'sec-3': { score: 7, maxScore: 10, percentage: 70 },
      'sec-4': { score: 7, maxScore: 10, percentage: 70 },
      'sec-5': { score: 8, maxScore: 10, percentage: 80 }
    },
    evaluatedAt: '2026-09-16T10:45:00Z'
  }
];


